### ISSUE TITLE
Scrollbar for Skill page

### ISSUE THREAD

**Issue by Ylgnik** [StardewModders/mod-ideas#1008]
With all the new skills out there, I feel like this is needed. Things just run off the page and don't look too great.

**Comment by Ylgnik** [comment]
Should I do one there or? Sorry new to how github works. Guessing PR is pull request?

**Comment by spacechase0** [comment]
I just wanted to leave a note for anyone who might want to take this up about where to get started. 

Yes, A PR is a pull request.

**Comment by Shockah** [comment]
The PR is now a thing, now waiting for it to be merged.
https://github.com/spacechase0/StardewValleyMods/pull/340
