### ISSUE TITLE
Hourly Audio

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#1011]
Sometimes I get caught up doing activities and don't keep a good track of the in game time. I'd love to see a mod that plays a configurable game audio for every hour from 6 AM to 11 PM, and then a separate configurable audio sample for 12:00 AM, 1:00 AM, and 2:00 AM. Obviously, these sounds should only play if the player isn't asleep.

**Comment by JudeRV** [comment]
Yooo this sounds like a great idea!!! I'll start working on this tomorrow :D

**Comment by Bartholomue** [comment]
@JudeRV Just checking in after a period of absence to ask if you made any progress on tackling the mod idea? <3

**Comment by aedenthorn** [comment]
![Test_7-29-2023_4786403](https://github.com/StardewModders/mod-ideas/assets/13594584/c1be05c6-513a-4951-95c9-4e87871ae96f)
I made one

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/17607/

You can set hourly chimes by setting the hour to -1

**Comment by Bartholomue** [comment]
Thank you as always! You're amazing.
