### ISSUE TITLE
Faster Paths

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#1022]
The 0.1 speed modifier that paths give you is negligible, and makes crafting and placing said objects less rewarding than otherwise could be. I'd love to see a mod that (configurably) boosts the speed bonus to something like 0.3 or 0.5.

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/9344

**Comment by Bartholomue** [comment]
Thanks for that. I'm usually so good at skimming through Nexus, but I admit I missed this one.
