### ISSUE TITLE
Mod Idea💡

### ISSUE THREAD

**Issue by FarmerMuhammed** [StardewModders/mod-ideas#1026]
So , There's an old mod back to 2016
Its Xnb and the name is Adult Jas and Vincent
Can someone update it to 1.4 and 1.5 and convert it into a SMAPI mod?
Connect me on Gmail if yes
chldawymhmdamyn@gmail.com

**Comment by spacechase0** [comment]
No

**Comment by Pathoschild** [comment]
(If I recall correctly, that mod was against [the Nexus terms of use](https://help.nexusmods.com/article/28-file-submission-guidelines#Content_related_to_Child_characters) since it allowed romancing them.)
