### ISSUE TITLE
Batman Arkamn  knight floor is lava mod 

### ISSUE THREAD

**Issue by oscar575-create** [StardewModders/mod-ideas#1028]
This could be cool for the game to be harder but more fun and make the bat mobile more of a change to gain but still fun I think a floor is lava mod for Batman Arkamn knight would be cool if possblie.

**Comment by spacechase0** [comment]
This is for Stardew Valley mods.

**Comment by oscar575-create** [comment]
Is it to hard to do such thing jsut liel to know why?
