### ISSUE TITLE
a Legible Monies mod

### ISSUE THREAD

**Issue by cho0pera** [StardewModders/mod-ideas#1035]
I humbly request an HUD tweak to add commas or dots to rhe gold/money display. As it is now, it is difficult to read quickly because there is no spacing between the digits. Ex. G  1207915 --> G  1,207,915.

At the end-of-day money count/profits breakdown screen there are commas (IIRC) and it's much easier to read the amount.

**Comment by aedenthorn** [comment]
![image](https://user-images.githubusercontent.com/13594584/213029528-c39a604e-0477-46a0-b93a-302d43a288d8.png)

How's this?

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/15123/
