### ISSUE TITLE
No more grass cutting with sword!

### ISSUE THREAD

**Issue by justiziabelle** [StardewModders/mod-ideas#1052]
It would be great if you couldn't cut grass with a sword, but only with scythe.

I got a really pretty farm, but it's on the wilderness map so in the evenings I get visited by nasty monsters and sometimes when I cut them down with my sword I accidently also cut grass or I have to move to not cut the grass and I got a lot of grass on my farm, because it's pretty, but it's not if I cut it down with my sword ugh.

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/15409/
