### ISSUE TITLE
Skip all quests

### ISSUE THREAD

**Issue by chronosh** [StardewModders/mod-ideas#1053]
It's tiring having to do the same quests every new save I wish to just skip quests that can't be skipped (build a coop 😭) or at least make them ask for something different like in help wanted quests...

**Comment by cho0pera** [comment]
You _can_ skip the Build a Coop quest! Open your journal, open the quest, click the little X to delete it.

**Comment by chronosh** [comment]
> You _can_ skip the Build a Coop quest! Open your journal, open the quest, click the little X to delete it.

Oh my lord hahaha I feel so dumb now but thank you so much xD
