### ISSUE TITLE
Show Farm Type on Save Entry

### ISSUE THREAD

**Issue by StardewSweetheart** [StardewModders/mod-ideas#1064]
I name all my farms and characters the same in every save. While I generally remember the details for each save, it would be super cool to be able to show a tiny version of the farm type image somewhere on the save entry like how the season is shown in the attached screenshot thanks to [this mod](https://www.nexusmods.com/stardewvalley/mods/14382). Maybe the 'Farm' string could be removed to make room for another image?

<img width="1209" alt="Screen Shot 2023-02-19 at 1 38 24 AM" src="https://user-images.githubusercontent.com/106191569/219940394-f9bcd961-20e1-447e-b006-217ee8069a41.png">

**Comment by Shockah** [comment]
[Custom Farm Loader](https://www.nexusmods.com/stardewvalley/mods/13804) does that.

**Comment by StardewSweetheart** [comment]
Hurray! Thank you!
