### ISSUE TITLE
Pigs grow up faster

### ISSUE THREAD

**Issue by StardewSweetheart** [StardewModders/mod-ideas#1070]
Right now pigs take quite a few in-game days (it feels like 2 weeks????) to grow up. Would be great to have them come of truffle-hunting age much sooner, perhaps within 3 to 5 in-game days.

**Comment by cho0pera** [comment]
I think you can easily tweak that if you want with your own lil CP mod. Just make a manifest, add something like this to the content.json, and have speed-grow pigs. 


`{
    "Format": "1.28.0",
    "Changes": [ 

            {
                "Action": "EditData",
                "Target": "Data/FarmAnimals", //0=days to produce, 1=days to grow, 24=sell price
                "Fields": {

                    "Pig": {0:"1",1:"5",24:"16000"},
			}
		}
	]
}
`

**Comment by StardewSweetheart** [comment]
Wonderful! Thank you so much!
