### ISSUE TITLE
Breaking up long loads into several smaller ones for high mod count games?

### ISSUE THREAD

**Issue by HannaCatherineVictoria** [StardewModders/mod-ideas#1071]
As I understand it part of that is because they load so much than can realistically be used in a short session- heck long sessions if you have enough mods. So, what about a mod specifically for high mod-count games that breaks that time up?

One example: taking a mod like say Ridgeside & have it check to see who's coming to town that day, load them, and then load both gondola stations, and whatever Ridgeside stuff is in the farmers inventory/chests. If a person gets on the gondola then the rest would load, and the game might very well end up in a black 'load' screen if they get to the exit of the Ridgeside gondola station map before it's done loading but it would be shorter, yeah? And likely cut off a chunk of load time for people who have Ridgeside, East Scarp, Downtown ZuZu, and so on?

There are also probably other mods that could be loaded piecemeal on an as needed basis, but those are less obvious to point out then something like a big mod like Ridgeside or East Scarp. 
Like... I guess the old PPJA project could load first, what the farmer has as inventory, what's planted, what's in whatever shops are loaded? and whatever is called up by say The Traveling Merchants cart, or mods that act like it: just picking a handful of things from a set of categories?? (am I even still getting how these work right at this point? Imma tap out for now, while I still make some sense. I hope)

One last thing: remember that blank load screen I mentioned? An additional thing- actually it could be its own mod? Loading screens. Like even just a bunny hoping around a black void is better than just a black void? ...I'll go ask Plurffle what they think of that one.

**Comment by Shockah** [comment]
I'm afraid Stardew already loads only the content it needs to; it doesn't help, that a lot of stuff unrelated to each other is put on the same texture though.
Maps are also only loaded on demand, but because NPC pathfinding is a thing, a lot of them have to be loaded most of the time.

**Comment by Entoarox** [comment]
Not possible to due technical limitations of how the game works.
