### ISSUE TITLE
An Update to the Festival End Time Tweak Mod

### ISSUE THREAD

**Issue by StardewSweetheart** [StardewModders/mod-ideas#1081]
[This](https://www.nexusmods.com/stardewvalley/mods/2966) wonderful mod has been broken for a while. If anyone is open to adopting it and giving it a refresh, that would be amazing.

**Comment by Shockah** [comment]
Does this unofficial version not work? https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-3.142524/page-78#post-3344462

**Comment by StardewSweetheart** [comment]
Oops, I didn't realize that existed! Thank you!

**Comment by Shockah** [comment]
https://smapi.io/mods to the rescue!
