### ISSUE TITLE
Ability to Access the Movie Theater w/o a Ticket

### ISSUE THREAD

**Issue by StardewSweetheart** [StardewModders/mod-ideas#1088]
It feels silly that I have to have a ticket to enter the theater and that I can only do it every so often. Would love to be able to go inside so I can play the damn crane game without a ticket, but need the ticket to see the movie/take a friend!

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/16395/

**Comment by StardewSweetheart** [comment]
thank you so much!!!!
