### ISSUE TITLE
Remove time limit for Special Orders?

### ISSUE THREAD

**Issue by jheuck** [StardewModders/mod-ideas#1089]
Sorry if this has already been asked but, as the title suggests, I wanted to know if it was possible to stop special orders from failing after a certain amount of days.

Time limits tend to stress me out so this kind of takes the fun away from a relaxing, chill game for me... I'm also very forgetful so I'd appreciate it if I could just complete these orders at my own pace rather than realizing that I've left it until the last day to complete it...

Something like [QuestDelay](https://www.nexusmods.com/stardewvalley/mods/1239) would be ideal.

If possible, it would be great if it would work with mod-added special orders as well, such as the ones in RSV or [Holiday Special Orders](https://www.nexusmods.com/stardewvalley/mods/10410)

I assume there must be a technical reason as to why someone hasn't already looked into this but I thought I'd ask.

Thank you to anyone who reads this! 😃

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/16403/

**Comment by jheuck** [comment]
Hot DAMN that was fast!! You're an absolute legend, @aedenthorn!! Hope you know that!!
