### ISSUE TITLE
Lets Go Fishing, Chum

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#1118]
I'd love the ability to create chum that you can apply to a tile of water to instantly generate fishing bubbles at that position. Could have varying items or qualities, providing differing duration based on the product used.

**Comment by aedenthorn** [comment]
This does basically what you are describing https://www.nexusmods.com/stardewvalley/mods/17581/

**Comment by Bartholomue** [comment]
Thank you! I was thinking some more complexity for the ability to generate bubbles at will, but this will definitely work. :D
