### ISSUE TITLE
Hydroponic Garden Pots

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#1119]
I'd like to see a mod for garden pots that would allow them to be placed on a water tile. Placed thusly, they'll always be watered (as if they had a built in sprinkler).

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/17582

**Comment by Bartholomue** [comment]
Sweet! Thanks for the swift response! You're the best.
