### ISSUE TITLE
Useful Pets!

### ISSUE THREAD

**Issue by RyuuInu** [StardewModders/mod-ideas#112]
UPDATED: This idea “Useful Pets!” Has been seen on NEXUSMODS as “CatGifts” (https://www.nexusmods.com/stardewvalley/mods/2132) . 
So this mod idea has been REVISED and is as follows: 
Have you ever wished that your dog was USEFUL or more LOVEABLE? If so, you are not the first. This mod idea includes a few functions that would make owning a dog be a much more rewardable experience.
- Useful Pets would include functions like
*1 Your dog can find items by digging them up (some artifacts/minerals/forageables)
*2 The higher your relationship with the dog, the better items they get you.
*3 The dog can do more interactive things like... Playing fetch (throw an item and the dog will retrieve it) The dog can scare off crows. Finally you’d have to buy dog food for your dog at Pierre’s. Possibly give the dogs commands like the following: sitting/staying/following/roaming(normal)

**Comment by RyuuInu** [comment]
Also add more functions. The dog will walk around with you a bit. You must fEED the dog with dog food (Pierre’s) and the dog can be walked maybe? (Follow me function listed above) it would also be cool to be able to tell your dog to sit and lie down.

**Comment by TrentXV** [comment]
https://www.nexusmods.com/stardewvalley/mods/3313 
I believe someone has already worked on that.

**Comment by Pathoschild** [comment]
Done by [Cat Gifts](https://www.nexusmods.com/stardewvalley/mods/2132) (which works with the dog too) and [Pet Choice Perks](https://www.nexusmods.com/stardewvalley/mods/3313)! If you want one of the suggested features they don't handle (like playing fetch), feel free to add a separate ticket for those.
