### ISSUE TITLE
Lucky shorts on mayor's statue

### ISSUE THREAD

**Issue by Nom0ri** [StardewModders/mod-ideas#1128]
What if we could show both the spending habits and nighttime adventures of our Mayor to the whole town at the same time? Let's put those shorts on the statue! It'd be best if we could click on the statue with shorts in hand to apply the change. And maybe some changes to the resulting event?

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/17642/

**Comment by Nom0ri** [comment]
If anyone would do it I knew it would be you hah
