### ISSUE TITLE
Metal and mineral wines/drinks

### ISSUE THREAD

**Issue by RabidMuffins** [StardewModders/mod-ideas#1148]
I was thinking that it would be an interesting idea to have a mod that would allow you to use your excess metals and/or gems to create wines or drinks. These could be intended for dwarves or people with a taste for rocks like Abigail!

**Comment by cho0pera** [comment]
Abigail, how'd you get in here?! /jk

**Comment by o0MrPro** [comment]
here you go: https://www.nexusmods.com/stardewvalley/mods/18405

**Comment by RabidMuffins** [comment]
> here you go: https://www.nexusmods.com/stardewvalley/mods/18405

Thank you so so much! <3

**Comment by RabidMuffins** [comment]
> here you go: https://www.nexusmods.com/stardewvalley/mods/18405

What do you think about adding metals to that? I love all the minerals! <3

**Comment by o0MrPro** [comment]
> > here you go: https://www.nexusmods.com/stardewvalley/mods/18405
> 
> What do you think about adding metals to that? I love all the minerals! <3

do you mean artifacts? if so I'll happily do so :)

**Comment by RabidMuffins** [comment]
> > > here you go: https://www.nexusmods.com/stardewvalley/mods/18405
> > 
> > 
> > What do you think about adding metals to that? I love all the minerals! <3
> 
> do you mean artifacts? if so I'll happily do so :)

I mean like copper, iron, gold, and iridium. It could even be smelted ingots instead of the ores.

**Comment by RabidMuffins** [comment]
> here you go: https://www.nexusmods.com/stardewvalley/mods/18405

Thank you again! So much! <3

**Comment by o0MrPro** [comment]
> > > > here you go: https://www.nexusmods.com/stardewvalley/mods/18405
> > > 
> > > 
> > > What do you think about adding metals to that? I love all the minerals! <3
> > 
> > 
> > do you mean artifacts? if so I'll happily do so :)
> 
> I mean like copper, iron, gold, and iridium. It could even be smelted ingots instead of the ores.

added in the latest update!
you are very welcome <3
