### ISSUE TITLE
Miraidon/Koraidon horse retexture

### ISSUE THREAD

**Issue by WolfSnek-Emerald** [StardewModders/mod-ideas#1169]
looking for a mod to replace horse with Koraidon or Miraidon from Pokemon Scarlet and Violet

**Comment by Silverinnia** [comment]
I love Miraidon so I can definitely do that. Will probably eventually do Koraidon too, but definitely Miraidon.

**Comment by Silverinnia** [comment]
Miraidon is done. Might be longer before I get to Koraidon.

https://www.nexusmods.com/stardewvalley/mods/20245

**Comment by Silverinnia** [comment]
And here's Koraidon.

https://www.nexusmods.com/stardewvalley/mods/20297
