### ISSUE TITLE
Genie Lamp, wish for ANY ITEM in the game! Can pay commission, more details inside.

### ISSUE THREAD

**Issue by Dragonfabri** [StardewModders/mod-ideas#1180]
Hi all! I was wondering if anyone could make a "simple" mod for me, i'll make it worth your while!

If you have already published mods on Nexus/Steam, link them and i can pay you beforehand! Otherwise i'll try it first, then pay you once all is in order.

Anyway, i'd like the following mod:

GENIE LAMP
Consumable item that, once used, opens a prompt to put in any item ID/Name to have a single copy of such item spawn! The lamp however requires 1 BILLION GOLD (1 Million gold sell price, stackable) to buy from a merchant.

The must-have features:

-) MADE FOR 1.6
Making use of its new Item ID logics and fully compatible for it 

-) COMPATIBLE WITH ALL 1.6 MODS
With the new ID system this should sinply translate to "insert modded item id here", but i'm no expert .

-) NO ITEM RESTRICTIONS: Any items that literally can't be spawned (or which crash the game if spawned) should be exempt from this ofc.

-) Able to spawn mod items (but i guess those have IDs too)

I know there's already CJB Item spawner mod, but i'm requesting this mod for two reasons: the former mod isn't able to give you LITERALLY any item in the game (and thanks to Shockah i can see why now!), and secondly, i want a way to access these items without really cheating, by instead having to ammass a fortune for just a single lamp shot at these items, let alone many!

Thanks in advance! My discord is Dragonfabri#1829

**Comment by Shockah** [comment]
The problematic items are problematic for a reason.

**Comment by Dragonfabri** [comment]
> The problematic items are problematic for a reason.

Well yeah, but since the CJB spawner can still spawn them, i don't see why to exclude them here. Unless they literally crash the game ofc

**Comment by Shockah** [comment]
What you see in CJB is what it can spawn at all. The problematic items are not problematic because they crash the game, but because it's not possible to spawn them in without cooperation from the mod that adds them.

**Comment by Shockah** [comment]
For what it's worth, the upcoming version of the game (1.6) has tons of changes under the hood to how items work and are constructed, which should make this easier, although it's still possible to have some outliers.

**Comment by Dragonfabri** [comment]
> For what it's worth, the upcoming version of the game (1.6) has tons of changes under the hood to how items work and are constructed, which should make this easier, although it's still possible to have some outliers.

I see, so would you suggest waiting for 1.6, installing the alpha or just commission it for 1.6 compatibility?

**Comment by Shockah** [comment]
I'd honestly suggest not asking for the impossible, aka spawning "literally any item", but also waiting for 1.6. And then commission just the Genie / UI part of it, for whatever is actually possible to spawn in a relatively simple way (which should still include more things than it currently can).

**Comment by Dragonfabri** [comment]
> I'd honestly suggest not asking for the impossible, aka spawning "literally any item", but also waiting for 1.6. And then commission just the Genie / UI part of it, for whatever is actually possible to spawn in a relatively simple way (which should still include more things than it currently can).

Solid advice, thank you! Will edit it then to account for "as many items as possible" plus 1.6 compatibility only

**Comment by aedenthorn** [comment]
![image](https://github.com/StardewModders/mod-ideas/assets/13594584/dbe85bb6-2958-4002-95a6-e0a04e8f3303)
This works, except for items that have the exact same display name (e.g. Wallpaper)

**Comment by Dragonfabri** [comment]
> ![image](https://private-user-images.githubusercontent.com/13594584/295047704-dbe85bb6-2958-4002-95a6-e0a04e8f3303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTIwMTksIm5iZiI6MTcwNDc1MTcxOSwicGF0aCI6Ii8xMzU5NDU4NC8yOTUwNDc3MDQtZGJlODViYjYtMjk1OC00MDAyLTk1YTYtZTBhMDRlOGYzMzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDIyMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMWU2NGJiMzk5ODIwNmU5OTJhZGRlZDcyNjQ1YWJhYWQ0NmZkZjQ3YTYxNDE0N2NiOWRhNmQyNWNlNzhjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4oHqrH8ClXU7lsVuTqeB8D-Uf-bb6fUOtIYNe0Wwes) This works, except for items that have the exact same display name (e.g. Wallpaper)

So quick! And looks perfect! Can you share it?

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/19794

**Comment by Dragonfabri** [comment]
> https://www.nexusmods.com/stardewvalley/mods/19794

My goodness, you rock! It's even made for 1.6! I'll be the first to test it once that version comes out, you have been amazing, and amazingly fast too!

**Comment by Dragonfabri** [comment]
> https://www.nexusmods.com/stardewvalley/mods/19794

Oh by the way, i can commission Kedidili to make a Genie Lamp item that does what your mod does, with its own item sprite and sold for absurd amounts of money.
Is it fine if i were to commission such a mod? Of course credit would be given, or maybe you can contact Kedidili herself and see which of you would like to publish it under their name, but let me know!

**Comment by WitheredSouls1** [comment]
You could check here for any possible comms

https://stardewmodding.wiki.gg/wiki/Stardew_Mod_Commissions

**Comment by Dragonfabri** [comment]
> You could check here for any possible comms
> 
> https://stardewmodding.wiki.gg/wiki/Stardew_Mod_Commissions

Thank you, that's the list i checked and found Kedidili!
