### ISSUE TITLE
Mod monitoring for multiplayer

### ISSUE THREAD

**Issue by Takakage** [StardewModders/mod-ideas#1193]
As 1.6 approaches as fast as snakes in the floor 85 of the dangerous version of skull cavern, I find myself in a conundrum my skill level doesn´t allow me to resolve, one of the players we like to play multiplayer with, likes to use balance breaking mods, such as the CBJ cheat menu, which ends up ruining the overall experience, because of course you speedran the mines to floor 120 in the first day it open when there is not enough food to even cut all the wood we need, what Id like to have is a mod that allows the farm owner to monitor which mods the guests are using, and either disable them or punish the player in a way a mod cannot fix, such as messing all the text so its on junimo text or something, am I too tyranical? is that mod too hard to build? (as a note, no, he wont quit using the mods, and no, we can't exclude him)

**Comment by Shockah** [comment]
Just… stop playing with that person, if they’re willing to break the rules of your playthrough?

**Comment by Traehgniw** [comment]
Something like this could still be useful - some kind of mod-match enforcer?

**Comment by tiakall** [comment]
Someone actually made this - I guess 1.6 made it possible https://www.nexusmods.com/stardewvalley/mods/25446

**Comment by Shockah** [comment]
Nothing changed, Entoarox is right. One could easily write a mod that overrides the broadcasted list of mods.

**Comment by Entoarox** [comment]
> Someone actually made this - I guess 1.6 made it possible https://www.nexusmods.com/stardewvalley/mods/25446

What that mod does was already possible, but as @Shockah mentioned, the list of installed mods has to be willingly handed over by the client - so nothing stops a mod installed on that same client from hiding itself and possibly other mods from the list.

Clients in the SDV multiplayer model simply have too much trust to prevent cheaters from cheating, and nothing short of completely replacing the networking SDV uses can even try to fix that.

**Comment by Pathoschild** [comment]
SMAPI sends a list of installed mods on connect to enable features like network messaging. While it's easy to circumvent mod detection if you know how (e.g. by editing mod manifests), that (a) is not something that the vast majority of players would know how to do and (b) will break some mods. So anti-cheat mods that work for the vast majority of players are sufficient to address this request.
