### ISSUE TITLE
No Coal for Fish Smoker

### ISSUE THREAD

**Issue by Cornish-Kap** [StardewModders/mod-ideas#1202]
Nice simple one (i hope) mod

Simply put I'd like a mod that makes the fish smoker not take any coal (alternatively make it use wood instead) 

You could also add extra configs to adjust how long it should take and such but thats up to you!

Please someone make it happen! 

Sincerely Cornish

**Comment by darkdreamer4912** [comment]
Working on this

**Comment by darkdreamer4912** [comment]
Done!
https://www.nexusmods.com/stardewvalley/mods/21346

**Comment by Cornish-Kap** [comment]
oh my god i just saw it on nexus you are amazing thank you!
