### ISSUE TITLE
Larger fridges

### ISSUE THREAD

**Issue by Skqrb** [StardewModders/mod-ideas#1211]
Make fridges have as much space as a big chest. No other special features, just bigger space. 

Please, if anyone could make this, it would be awesome. Thank you!

**Comment by Entoarox** [comment]
Please clarify your request:
Do you mean all fridges (Including the custom ones you can place down) or only the built-in ones?

**Comment by Skqrb** [comment]
I thought all fridges were the same, but I was specifically referring to the mini fridges that you buy from Robin and place down. My request is for them to go from 36 slots to 70.

**Comment by Entoarox** [comment]
> I thought all fridges were the same, but I was specifically referring to the mini fridges that you buy from Robin and place down. My request is for them to go from 36 slots to 70.
The built-in fridges are handled in a slightly peculiar way hence the question.
It should be more then possible to handle both the built-in ones and mini-fridges, but clarification was still needed to make sure things did not go wrong. :)

**Comment by Skqrb** [comment]
Oh, my bad, I didn't know that! But thank you very much!

**Comment by Entoarox** [comment]
I think I will see about taking on this request, I happen to have unexpected free time to do so, and it should not be a difficult one.

It may take me a few days to get it properly coded up, as I wish to ensure that no unexpected edge-cases are involved, and testing to make sure of that always takes a lot of time.

**Comment by Entoarox** [comment]
I've got the fridges to be bigger, unfortunately getting the UI to reflect their new size is proving challenging, but I am working on it!

**Comment by Entoarox** [comment]
Got it finished surprisingly quickly, only hickup turned out to be getting the UI to behave!
https://www.nexusmods.com/stardewvalley/mods/21678/

**Comment by Skqrb** [comment]
That was amazing!!!! Thank you SO MUCH!! I just tested it and it's perfect, exactly what I had in mind, you're incredible! Thank you very much once again, have a wonderful day <3
