### ISSUE TITLE
Fish Jellies Converter Mod

### ISSUE THREAD

**Issue by 2njs6902** [StardewModders/mod-ideas#1218]
I noticed that I'm accumulating a lot more river jellies rather than the other two types and thought it would be nice to have a mod that can create a crafting recipe or a machine that converts the jellies. It cold work that sea jellies can be converted into river jellies, river jellies into cave jellies and cave jellies in to sea jellies. But of course if there is a better/preferred way to do this then it doesn't matter to me. Thanks in advance!

**Comment by sarahvloos** [comment]
[Transmute (Jelly)](https://www.nexusmods.com/stardewvalley/mods/22877/)

Three new recipes that let you transmute two jellies of one kind (following your idea of conversions) into one of the other. 2 Cave Jellies = 1 River Jelly, etc. As with every recipe in the game, you need to craft each at least once to get the Craft Master achievement.

**Comment by 2njs6902** [comment]
Thank you so much!

**Comment by 2njs6902** [comment]
Thank you so much!
