### ISSUE TITLE
Harvest bubbles for mossy trees

### ISSUE THREAD

**Issue by Cornish-Kap** [StardewModders/mod-ideas#1222]
So I really like having the Harvest and Water bubble mods and I would love it if someone could make a harvest bubble for Mossy Trees as well!. The only issue I could see is with tappers but if possible you could make the moss bubble appear above it!

Please! someone make this real! (I've tried modding myself but its too big brain for me so ima leave that to the pros)

With Moss Loving Regards
/Cornish

**Comment by kqrse** [comment]
I might take you up on this idea. I find that I never notice moss unless it's a green rain day, so maybe this is the sort of thing I need.

**Comment by kqrse** [comment]
https://www.nexusmods.com/stardewvalley/mods/22818

Looks like someone did for you

**Comment by Cornish-Kap** [comment]
Thank you Tocseoj for making this! closing the issue!
