### ISSUE TITLE
Split Screen Manager 

### ISSUE THREAD

**Issue by SazanamiKage** [StardewModders/mod-ideas#1226]
https://www.nexusmods.com/stardewvalley/mods/12063?tab=description

The official mod for a split screen manager currently does not work with the latest version of SMAPI and SDV. This is a suggestion for a new mod that allows for managing customization of split screens in multiplayer, or an unofficial update of the out-dated mod. 

Thank you :)

**Comment by Smoked-Fish** [comment]
I made my own version of the idea

[Split Screen Manager - https://www.nexusmods.com/stardewvalley/mods/23669](https://www.nexusmods.com/stardewvalley/mods/23669)
