### ISSUE TITLE
Particle Framework

### ISSUE THREAD

**Issue by Lunar0s** [StardewModders/mod-ideas#1239]
A framework that can be used to add particles to furniture, tiles, npcs, objects, weapons and etc.

**Comment by Smoked-Fish** [comment]
Updated aedenthorn's particle framework mod for 1.6
[Particle Framework - https://www.nexusmods.com/stardewvalley/mods/23544/](https://www.nexusmods.com/stardewvalley/mods/23544/)

**Comment by Lunar0s** [comment]
> Updated aedenthorn's particle framework mod for 1.6 [Particle Framework - https://www.nexusmods.com/stardewvalley/mods/23544/](https://www.nexusmods.com/stardewvalley/mods/23544/)

Can I use it on furniture?

**Comment by Smoked-Fish** [comment]
Updated it, supports furniture now too

**Comment by Lunar0s** [comment]
This is perfect!!

Thank you again.
