### ISSUE TITLE
On/off toggle or skin for heads up display

### ISSUE THREAD

**Issue by s0methingw1tty** [StardewModders/mod-ideas#1241]
I would love a mod that lets me toggle on/off the in game heads up display that shows the season/date/time/weather. Or a skin that makes it much smaller and simpler visually. I dislike how much space it takes up when I'm zoomed out, but I'm not motivated to teach myself programming just to change it. Anyone think this would be an interesting project?

**Comment by Smoked-Fish** [comment]
I am interested in this. I think I will start working on this

**Comment by Smoked-Fish** [comment]
[HUD Customizer - https://www.nexusmods.com/stardewvalley/mods/23704/](https://www.nexusmods.com/stardewvalley/mods/23704/)

Plan to add more features but for now you can disable the Date/Time/Money HUD with it
