### ISSUE TITLE
craftsman's belt

### ISSUE THREAD

**Issue by takodashi** [StardewModders/mod-ideas#1244]
a belt that can hold all the tools in a single slot, and that can unfold a wheel with the right click to select the tool to use.

(tools can be inserted and extracted from the inventory just like bait or tackle from the fishing rod)

**Comment by Saah7** [comment]
[Omni-Tools](https://www.nexusmods.com/stardewvalley/mods/14865) ([Unofficial 1.6 update](https://github.com/aschismatism/aedenthorn-StardewValleyMods/releases/tag/OmniTools-1.0.3-unofficial))
