### ISSUE TITLE
expansion to interior of farmhouse? making living room or spare room larger.

### ISSUE THREAD

**Issue by heavenlyhoney** [StardewModders/mod-ideas#134]
hi hello!!! i'm having an issue furnishing my house as i would like to. i would really love a **spacious living area** with the flat screen tv + etc. this can be either the "living room" or the spare room above the kitchen!! or both!!! i know this is more cosmetic so it's rly considered minor but i love this idea a lot!! ♡♡

**EDIT:**

i'd really love if there could be an included flavor of this mod where it removes spouse rooms as well!! thank you ♡

**Comment by ja450n** [comment]
Looking into this, it seems re-arranging the house affects some things that would need to be changed to accomidate new X,Y coords of things:

- FarmHouse door warp position for where player exits house. Set in tbin itself.
- Game Code: Locations.getBedSpot - position of where the player wakes up, based on upgradeLevel.
- Game Code: Locations.getEntryLocation - position of where player is placed upon entering the house, based on upgradeLevel.

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/3704

As of right now changing the main rooms still cannot be done via Content Patcher, but here's my take on a larger farmhouse, with a large basement room for decorating or storage.
