### ISSUE TITLE
Save mail & notes

### ISSUE THREAD

**Issue by logan97alexander** [StardewModders/mod-ideas#135]
It'd be great if there was a way to reread your mail and the notes you find in various places! Maybe a dedicated inventory tab that just has all the papers you've gotten so far? If possible, the ability to accept mail quests you accidentally clicked away from via the mail inventory would be great too, but if that isn't feasible, just the inventory itself would be a big help.

**Comment by Felix-Dev** [comment]
Had a similar idea. Currently started looking into it.

**Comment by Pathoschild** [comment]
@Felix-Dev Are you still working on this?

**Comment by Felix-Dev** [comment]
@Pathoschild Currently not working on the mod. Anyone interested can start picking it up. I do have some concept/code ready for those interested.

**Comment by minervamaga** [comment]
Deprecated by SDV 1.4
