### ISSUE TITLE
Dressers act as chests

### ISSUE THREAD

**Issue by miome** [StardewModders/mod-ideas#140]
I'd like to be able to use the furniture that appears to be for storage (ie has drawers), to act like chests and let us store stuff in them.   It would make it a lot more fun to decorate your house when the decorations are also useful.   A couple of bonus ideas:
Make an animation of the top drawer opening, much like the chest lid opens
Have the item(s) in the first 1-3 slots be displayed on top of the furniture.

**Comment by minervamaga** [comment]
Deprecated by SDV 1.4 - vanilla dressers now hold clothing items
