### ISSUE TITLE
Crab pots can give higher-quality items

### ISSUE THREAD

**Issue by trantula45** [StardewModders/mod-ideas#145]
Why is it that the fish you get from the crab pot are always normal quality? I think you should have a chance of getting silver, gold or even iridium quality crabs etc from the crab pots.

**Comment by ja450n** [comment]
This is a great idea! 
I'm doing some pre-release play-testing of a mod that implements this.
https://github.com/ja450n/StardewValley-BetterCrabPots

**Comment by trantula45** [comment]
Does that mod work? If so I’d be interested in using it.

**Comment by trantula45** [comment]
So far it’s working pretty well, but is it possible to incorporate your fishing level to the chances of getting higher quality items by chance also?

**Comment by Pathoschild** [comment]
@ja450n Are you still working on this?

**Comment by AndyCrocker** [comment]
Due to there being no response I'm going to assume it was discontinued. 
So I'll just say BetterCrabPots has this feature: https://www.nexusmods.com/stardewvalley/mods/3159
