### ISSUE TITLE
Earn Tokens When Playing the Arcade Games

### ISSUE THREAD

**Issue by add-booknerd** [StardewModders/mod-ideas#149]
I was thinking that you should be able to earn tokens that let you enter a "lucky dip" that gives you a random product/seed. Perhaps you could earn one token for every 10 coins you finish the game with?

**Comment by OfficialRenny** [comment]
Been working on something after I saw this suggestion and I think I'm nearly done with it (Took a 2 week break so couldn't finish it earlier). Will give an update when it's finished.
