### ISSUE TITLE
Less Exhausting Calico Spin

### ISSUE THREAD

**Issue by pcsbx** [StardewModders/mod-ideas#15]
Calico Spin takes a lot of time per each spin, and since one needs to play dozens of spins to reach worthwhile wins, it gets super tedious. It can't be played totally off-hand either if one intends to win more than lose. This is painful for anyone who needs/wants a pile of Qi coins because outside of buying with gold, Calico Spin is the most effective way to get qingaling with Qi coins.

Possible solutions:
- speed up/shorten the spin animation
- additional, higher bet levels

**Comment by Jonqora** [comment]
[Fast Animations](https://www.nexusmods.com/stardewvalley/mods/1089) mod fits the bill for this one, allowing configurable animation speed for calico spin (and several other animations in the game)
