### ISSUE TITLE
Mod Idea: The statue of generosity

### ISSUE THREAD

**Issue by Shyguygeek** [StardewModders/mod-ideas#153]
It's like the Statue of Endless Fortune but silver. What it does is gives you a random loved gift every day except on birthdays then it will give out theirs every time.

**Comment by Shrek5InTheatres2019** [comment]
I'll look into creating this one

**Comment by Shadowfoxs** [comment]
I am thinking about this.

**Comment by paradigmnomad** [comment]
![SilverStatue](https://user-images.githubusercontent.com/34044924/84610869-23f1f200-ae8a-11ea-9dd2-953b1c564575.png)

Silver Statue of Endless Fortune.

**Comment by spacechase0** [comment]
Done, will publish soon

**Comment by spacechase0** [comment]
Sorry I didn't publish this sooner. https://www.nexusmods.com/stardewvalley/mods/7532
