### ISSUE TITLE
10-heart benefits

### ISSUE THREAD

**Issue by atkup** [StardewModders/mod-ideas#156]
I always found the accomplishment of achieving 10-hearts with villagers very unrewarding (aside from the achievements and cutscenes you might not care for)... So I wanted to share some ideas for a mod to buff those benefits and better incentivize players to pursue this goal:

- Replenishing energy from talking to villagers at 10-hearts per interaction (spouse replenishes more!)
- Passing out outside having a chance to be rescued by a villager in the area for free instead (chance at 100% inside their house) and mailed with a note similar to the Joja bill but attached with a motivational snack instead
- Always having best daily luck on the birthdays of villagers at 10-hearts

**Comment by EpicBellyFlop45** [comment]
I'll start doing it now

**Comment by EpicBellyFlop45** [comment]
https://www.nexusmods.com/stardewvalley/mods/3605/
