### ISSUE TITLE
Mod: Community center bundles that use Json Assets items

### ISSUE THREAD

**Issue by megmom84** [StardewModders/mod-ideas#160]
This was done by one version of a mod in the past, with Longevity, however there are SO many more crops made with Json Assets these days (and you can make a lot of recipes and big craftables with them, so I prefer to use them) and I can't get Longevity's MCM to work properly anyway (in shops the seeds show as just the ground shadow and are invisible when planted, even though I've followed the install instructions beginning to end repeatedly on version 1.3.28 of the game and the SMAPI 2.7).

According to Pathoschild this Community Center bundle mod cannot be accomplished with a Content Patcher pack because of the dynamic IDs of crops and other items added with Json Assets, so a SMAPI mod would be required.

Another idea other than just crops being used would be for cooking recipes or even the flower arrangements from Farmer to Florist being required for a bundle (or tea from Tea Time if that mod were made compatible). Jewelry from the Jewelcrafting Json assets mod, Sweets from the Sweet Tooth Mod, beauty items from the Kawaii Valley json assets items.

I would be willing to work on this myself but I wouldn't begin to know how to make a true SMAPI mod. (Harmony, C#, Python what's that?)

**Comment by Pathoschild** [comment]
Json Assets has [an undocumented API](https://github.com/spacechase0/JsonAssets/blob/master/Api.cs) that can be used to get the ID given an item name. So essentially you'd need to store the bundle items by name (maybe with support for content packs), and adjust the bundles automatically after load to match the IDs returned by Json Assets.

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/3444
