### ISSUE TITLE
Housing colors

### ISSUE THREAD

**Issue by PKMN23** [StardewModders/mod-ideas#161]
A mod that would let you customize your house colors by going to Robin's, and entering Hexadecimal codes would be really cool!

**Comment by Dawilly** [comment]
I looked into this, and could do it pretty easily with Shaders targeting various colors. I'll look into applying it into MTN2, post college semester.

**Comment by PKMN23** [comment]
Sweet! Thank you so much!

**Comment by spotteddotted** [comment]
This has pretty much been done in the 1.5 update!
