### ISSUE TITLE
Smoker

### ISSUE THREAD

**Issue by Hotl3looded** [StardewModders/mod-ideas#162]
This mod would add a new Artisan Equipment to smoke fish and cheese.

How it would work:
1. Recipe for crafting smoker obtainable by increasing fishing skill and requires iron + coal to build
2. Requires 1 fish/cheese + wood in inventory (like coal for furnaces)
3. Takes a few days to smoke the fish
4. Increases the base fish/cheese value
5. Smoked fish/cheese value is influenced by artisan perk

This might help fishing and ranching compete with agriculture in the end game.

**Comment by paradigmnomad** [comment]
PPJA may pick this up for use with CustomFarmingRedux rather than a standalone SMAPI mod.

**Comment by Eeveereest** [comment]
Implemented in Artisan Valley.
https://www.nexusmods.com/stardewvalley/mods/1926

**Comment by minervamaga** [comment]
Artisan Valley now includes a smoker.
