### ISSUE TITLE
replace the terminated JoJa building

### ISSUE THREAD

**Issue by Pookachutf** [StardewModders/mod-ideas#174]
I hate walking past the empty Joja building after the community center is completed.. i dont even know if this is possible but I would love to see something- ANYTHING really but that sad building with its gaudy signs.

possible ideas-

community sports ball center
skate park
rose garden

**Comment by Entoarox** [comment]
This is a somewhat difficult task, as it involves messing with tiles that CA himself also edits, a action that due to the sloppy tile-editing code CA uses is error-prone.

Marking this as `medium` difficulty for that reason alone.

**Comment by minervamaga** [comment]
Karmylla's Maps remove the Joja ruins via Content Patcher. https://www.nexusmods.com/stardewvalley/mods/1149
