### ISSUE TITLE
An "Animals" tab in the menu

### ISSUE THREAD

**Issue by ACpeaches** [StardewModders/mod-ideas#177]
I'd love to see a Stardew mod that gives the player an "Animals" tab in the main menu, where you could find a list of all the animals you currently own, along with their information (name, age, # of hearts). This would be so helpful, instead of having to manually click on each individual animal to see their info, or having to manually count them.

I'm actually surprised this isn't a thing yet! It seems so simple and it would be such a convenience :)

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/3283/
