### ISSUE TITLE
Long Sleeves Shirt And No Sleeve

### ISSUE THREAD

**Issue by Yoseiri** [StardewModders/mod-ideas#18]
It would be nice to be able to switch between long sleeve shirt, no sleeve and the vanilla one, maybe work like the Get Dress mod, I can only do the sprite.

**Comment by KarBoy2314PL** [comment]
No sleeve is easy can be done with content patcher, long sleeve will probably need content patcher

**Comment by KarBoy2314PL** [comment]
[have you tried looking into this mod?](https://www.nexusmods.com/stardewvalley/mods/2416)

**Comment by KarBoy2314PL** [comment]
[Suns Out Guns Out - Sleeveless Shirts are done](https://www.nexusmods.com/stardewvalley/mods/3541)
