### ISSUE TITLE
Opening Geodes without Clint

### ISSUE THREAD

**Issue by FoggyWizard** [StardewModders/mod-ideas#182]
Add a way ---preferably as a machine, so that way the money saved by doing it yourself is balanced by time in the machine, and it can further be automated with the new Automate API--- to open geodes without using Clint or his shop. At all.

**Comment by EpicBellyFlop45** [comment]
I'll start doing it now

**Comment by LenneDalben** [comment]
It's not a machine, but strobel1ght created Personal Anvil, which lets you break your own geodes after you craft an anvil (and there's 2 different ways to get the recipe): https://www.nexusmods.com/stardewvalley/mods/5326
