### ISSUE TITLE
Fishy business

### ISSUE THREAD

**Issue by pcsbx** [StardewModders/mod-ideas#19]
- clean and stock ponds to grow the pond/lake fish you want, where you want

- craft or buy new traps for fishing, allowing multiple catch, trapping fish of various sizes, trapping eels, and so on

- farm bivalves on special structures

- fishing permits required for your off-property operations (seasonly/yearly fees)

- milk your sturgeons and salmons for caviar

**Comment by minervamaga** [comment]
Fish ponds were added to vanilla 1.4
