### ISSUE TITLE
Pet Choice Perks

### ISSUE THREAD

**Issue by Jason9896** [StardewModders/mod-ideas#192]
Small idea to have the choice of pet cat/dog add a small change to gameplay.
Choosing the Dog could Make farm animals happy faster
Choosing the Cat could reduce or eliminate crows

Petting the dog could add small duration(12 in game hours) buff to foraging skill
Petting the cat could add small duration(12 in game hours) buff to fishing skill

**Comment by skuldomg** [comment]
Working on it :)
