### ISSUE TITLE
Jukebox/stereo that can play the games soundtrack

### ISSUE THREAD

**Issue by Blushberrii** [StardewModders/mod-ideas#195]
A jukebox would be a piece of furniture that is interactive and would allow players to play songs from the soundtrack of the game automatically. And if other mods that give new music are downloaded, they can play those too! It can either be global, where the music is played on the entire map, or it can be only in one area, depending on what the players want.

**Comment by minervamaga** [comment]
Deprecated by the addition of the Mini-Juke in vanilla 1.4
