### ISSUE TITLE
Rarecrow collected Event

### ISSUE THREAD

**Issue by MrKrowely** [StardewModders/mod-ideas#197]
A mod that once all Rarecrows are collected AND placed on the farm, it makes the ENTIRE farm immune to Crows, no matter the size of the farm or the location on the farm that the Rarecrows are placed.

**Comment by EpicBellyFlop45** [comment]
I'll do it

**Comment by MrKrowely** [comment]
omg, YAY! TYVM! <3

**Comment by EpicBellyFlop45** [comment]
https://www.nexusmods.com/stardewvalley/mods/3232
