### ISSUE TITLE
crop bug event and pesticides

### ISSUE THREAD

**Issue by MrKrowely** [StardewModders/mod-ideas#198]
similar to the witch event for the void egg, say on year 2/3 and then every day/week past that has a chance for the bug event, thus needing a seasonal application of pesticides to prevent/cure a bug infestation event
and each day that it's not treated, it will spread by double across your field, but then have like 4 days until it would effect crop quality, and 7 days before it would destroy crop quality.
of course 4 day plants would be immune, and 6 day plants would never get destroyed, but those usually aren't the money makers anyways

**Comment by MrKrowely** [comment]
I'd be more than happy to help out whoever would be doing this one with the textures in photoshop, I have photoshop CS4

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/4446

Is this similar to what you wanted?

**Comment by minervamaga** [comment]
No answer to this issue, marking it closed.
