### ISSUE TITLE
More quests??

### ISSUE THREAD

**Issue by Blushberrii** [StardewModders/mod-ideas#203]
I've realized that I've been repeating quests again and again from the Daily Board, but I only do them because it helps me to enjoy the game and do something, even when you're practically finished with the game. 

Maybe this mod could give some more quests to the game, add some different ones. I would imagine that it wouldn't be that difficult. 

Thank you!

**Comment by EpicBellyFlop45** [comment]
Do you have any ideas for new quests?

**Comment by Entoarox** [comment]
This is marked as hard due to the quest system in SDV being very rigid and hard to modify.

**Comment by minervamaga** [comment]
SDV 1.4 adds new variety to the quests, closing
