### ISSUE TITLE
More storyline quests

### ISSUE THREAD

**Issue by SaltySam1** [StardewModders/mod-ideas#205]
I don't really know what to *actually* suggest, but I'd just think it would be a cool idea as it makes it funner for the late game people

(Maybe an add-on to the CC)

**Comment by Entoarox** [comment]
Marked as `medium` difficulty since it would require a whole new CC-style area to be created and relevant collection quests to be setup.

**Comment by minervamaga** [comment]
Post CC bundle and quest added by SDV 1.4
