### ISSUE TITLE
Show Fish quality after catch

### ISSUE THREAD

**Issue by MrKrowely** [StardewModders/mod-ideas#207]
a mod that will show you the quality of fish you just caught in the pop up thought bubble.
![fishcatchqualitymod](https://user-images.githubusercontent.com/5624886/51082600-d2ab6500-16cf-11e9-9553-f1108ab652d7.jpg)

**Comment by f4iTh** [comment]
So kind of something like this?
![fishqualityindicators](https://user-images.githubusercontent.com/34132723/51717999-d209bb80-204b-11e9-98e4-3bc505a9ef0b.png)

https://www.nexusmods.com/stardewvalley/mods/3326
