### ISSUE TITLE
New Outfit for Player Flower Dance Wedding

### ISSUE THREAD

**Issue by Ghastly0Koami** [StardewModders/mod-ideas#210]
It's something simple, I just feel it feels off how the player stays in the same clothes during the Flower Dance. While all the other NPCs have something different to wear. Also, it's kind of odd that you use your farm clothes at your wedding.

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/2864 can be used with Kisekae to add a Flower Dance outfit and wedding outfits.
