### ISSUE TITLE
Useful Copper Pan

### ISSUE THREAD

**Issue by TimeWandrer** [StardewModders/mod-ideas#212]
It would be nice if the copper pan was actually useful!

Could a mod be created the allows the copper pan to be used anywhere, not just the random sparkly spots?  It could fish out trash, ores, gems, geodes, artifacts?, or other rare items in the game.  Perhaps, the mod could also support JsonAssets so that additional gems/items could be made by players to be mined from the waterways of SDV? Also, it would be nice if the copper pan could actually be upgradable like the other tools so that different items could be found/mined more easily at different levels.

May be accomplished perhaps by using Teh's Fishing Overhaul framework with his permission?

**Comment by KarBoy2314PL** [comment]
and to expand on that, increase the probability for copper pan interact spots, as well as add xp depending on what you aquired - ores give mining, trash gives fishing, etc.

**Comment by BlatantDecoy** [comment]
See: https://www.nexusmods.com/stardewvalley/mods/4161
