### ISSUE TITLE
Make slimes useful either as furniture components, potion components or something similare

### ISSUE THREAD

**Issue by coolbond1** [StardewModders/mod-ideas#213]
Right now there really is no use for slimes so having an entire hutch for them is just wasted real-estate and resources.

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/3723

Is this similar to what you wanted?

**Comment by Balmmaker** [comment]
https://www.nexusmods.com/stardewvalley/mods/5678 This mod uses slime to make high quality jewelry. I have 2 slime hutches because of it

**Comment by minervamaga** [comment]
Closing because two mods have been offered without OP replying.
