### ISSUE TITLE
Have the Beehouse collect modded floral honeys.

### ISSUE THREAD

**Issue by AmburrBambii** [StardewModders/mod-ideas#214]
A mod that "helps" the beehouse notice modded flowers and create appropriately named honey. Could make it so that you could add in your own modded flowers, or even regular crops and make something like "cauliflower honey". You can also make it so that trees can influence honey names, "apple honey".

**Comment by minervamaga** [comment]
Changes to the vanilla game now makes modded flowers work with the vanilla beehouses.
