### ISSUE TITLE
Simple reverse transmutation mod, no extraneous features

### ISSUE THREAD

**Issue by AnonymousPepper** [StardewModders/mod-ideas#228]
Just a simple mod that adds the ability to turn iron into copper, gold into iron, etc, ideally by configurable ratios and able to potentially support mods that add other types of ingots.

There are of course already mods that do add such recipes, but all of them _also_ do all sorts of other things, to my knowledge, which, of course, also gets in the way of compatibility.

All I'd like to see is a simple, no-frills-besides-configurability down-transmute mod made for maximum compatibility for fitting into more heavily modded games.

**Comment by KarBoy2314PL** [comment]
I was going to mention [Equivalent Exchange](https://www.nexusmods.com/stardewvalley/mods/1656) but if you don't want anything else, adding recipes to things that already have recipes might cause trouble

**Comment by mytigio** [comment]
You can do this with just CP, I don't intend to release this one, you can if you like (you'll need to edit the manifest to make it your own thing), but I happen to have a personal mod that adds this and a bunch of other small tweaks, so I just stripped out my other tweaks to make you a bare bones version.

It also supports Prismatic Bars from the prismatic tools mod (iridium to prismatic bars and visa versa).

I've done very little testing with this stripped down version, but let me know if you need help tweaking it.
[[CP] Reverse Transmutation Recipes.zip](https://github.com/StardewModders/mod-ideas/files/3694577/CP.Reverse.Transmutation.Recipes.zip)
