### ISSUE TITLE
Further House Upgrades

### ISSUE THREAD

**Issue by minervamaga** [StardewModders/mod-ideas#230]
I'd like to see the ability to add further house upgrades via Robin.  Add an attic, add more rooms, etc.  Content Patcher supports patching conditions for custom upgrades, but currently there isn't a mod that adds them.

**Comment by Froststar11** [comment]
I'm currently doing a second story! From there we could easily do an attic. I just don't know what players would want to use the extra space for, so I'm not sure if I should partition it into rooms or leave it wide open. 

![image](https://user-images.githubusercontent.com/47826128/53146561-af978f00-3572-11e9-85ee-8fa29dc7cc11.png)

![image](https://user-images.githubusercontent.com/47826128/53146568-b4f4d980-3572-11e9-9f58-234c80706e60.png)

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/3731
