### ISSUE TITLE
Fix/Recreate Expanded Fridge mod

### ISSUE THREAD

**Issue by Froststar11** [StardewModders/mod-ideas#233]
The existing one is broken. But a mod that increases the capacity of the fridge (and even chests for that matter) would be much welcome. I'd like to be able to store everything I need to cook, including a stack of every crop, in the fridge. Someone want to take on that project?

**Comment by Pathoschild** [comment]
It's not quite the same, but [Remote Fridge Storage](https://www.nexusmods.com/stardewvalley/mods/2545) lets you create 'ingredient chests' which provide items for cooking like the vanilla fridge.

**Comment by Froststar11** [comment]
Yeah, then you have to junk up your kitchen with a ton of chests. It would be nice to have it all in the fridge. For now I'm using the Remote Fridge Storage mod, actually. But I'd love a better way if anyone wants to tackle this.

**Comment by ImJustMatt** [comment]
Expanded Storage can modify fridges (and chests) to hold infinite items
