### ISSUE TITLE
Scary sprinkler

### ISSUE THREAD

**Issue by KarBoy2314PL** [StardewModders/mod-ideas#242]
from #132

A sprinkler and a scarecrow combined so it fits all in one plot, sprinkler distance depends on what sprinkler you crafted it with (Don't know if you can check for that or if you want to make several versions or make one with a iridium sprinkler its up to you!)

TL;DR - Combine a Scarecrow and one of three sprinklers and you get a block that has the benefits of both. Good luck with UI Info Suite.

**Comment by Pathoschild** [comment]
See [Prismatic Tools](https://www.nexusmods.com/stardewvalley/mods/2428), whose prismatic sprinkler acts as sprinkler + scarecrow + lamp (configurable).
