### ISSUE TITLE
Allow one player to build more than one stable

### ISSUE THREAD

**Issue by KarBoy2314PL** [StardewModders/mod-ideas#244]
from #70

I was thinking multiple horses similar to how the more pets mod works, that way you can use a lot of replacements for maybe 10 horses a game.

3-month-late edit: Tractor mod adds a new "horse", so technically this is possible

**Comment by Entoarox** [comment]
As I already mentioned there, this would at the very least break compatibility with other mods which depend on the horse.

Further, the way horse & player seem to be connected does not support having multiple horses, although a deeper look into the mechanics is needed to know 100% if this is the case.

**Comment by Entoarox** [comment]
Deeper look done after being informed of things by Pathos, the game itself does not bind horses to players, extra horses would not interact with mods such as Horse Whistle, but should be technically possible.

**Comment by minervamaga** [comment]
Adopt & Skin (https://www.nexusmods.com/stardewvalley/mods/4011) allows you to find wild horses and adopt them.

**Comment by minervamaga** [comment]
#70
