### ISSUE TITLE
Farm Animal Data Accepting class items or json assets items.

### ISSUE THREAD

**Issue by TrentXV** [StardewModders/mod-ideas#248]
I would like to be able to create new animals that produce random items from a class. I tried making them work with a cathegory ID but it does not work.
Here's the log: https://log.smapi.io/6NfaYQ12
Also, they are not compatible with json assets as they only ready IDs from the objectinformation and will not rad any items created by json assets.

**Comment by Pathoschild** [comment]
@TrentXV This repository is for suggesting new mods. To suggest improvements to existing mods, I recommend adding a comment on their mod page. :)
