### ISSUE TITLE
Custom Recipes for Machines

### ISSUE THREAD

**Issue by TrentXV** [StardewModders/mod-ideas#249]
Create mod that lets you edit Vanilla Machines and Mills inputs and outputs, like adding a Grape to a cask you get Vinegar (without having to create new machines).

**Comment by KarBoy2314PL** [comment]
custom recipes made from JSON files?

**Comment by TrentXV** [comment]
Yes, if possible, just to make sure - Vanilla Machines using json assets items or other vanila items in Vanilla Machines or Mill to produce new items.

**Comment by TrentXV** [comment]
https://www.nexusmods.com/stardewvalley/mods/4970
