### ISSUE TITLE
A mod that adds a scarecrow and or sprinkler that cover the entire farm

### ISSUE THREAD

**Issue by MadCow667** [StardewModders/mod-ideas#253]
Can someone make a mod that adds a sprinkler and or scarecrow that covers the entire farm so I just need to place one of each then have free will to design the farm however i like without watering / worrying about crows?

**Comment by EpicBellyFlop45** [comment]
A mod I've made recently (BetterRareCrows: https://www.nexusmods.com/stardewvalley/mods/3232) Makes it so once all rarecrows have been placed crows no longer show up. You can use that for the meantime if you like while waiting for someone to pick up the idea

**Comment by Mizzion** [comment]
Here you go. You will need SMAPI and JsonAssets in order to get the Sprinkler and Scarecrow.

The Sprinkler costs 100 stone and the Scarecrow costs 100 wood. You can craft them.

https://www.nexusmods.com/stardewvalley/mods/3633/
