### ISSUE TITLE
Even more convenient/better shop menu.

### ISSUE THREAD

**Issue by skybellrock** [StardewModders/mod-ideas#255]
Theres an ever growing amount of mods and content coming to SDV, therefore i think we need a mod that makes every item in the shop menu take less space so you can see more items at a time. Looking for a specific item with alot of item mods is a pain rn, as you can only see 4 items at a time.

**Comment by KarBoy2314PL** [comment]
this may need a complete rewrite of all GUIs

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/2012

I believe this mod was updated with a grid option recently, is that something like what you were looking for?
