### ISSUE TITLE
Stop items from falling in water while fishing!

### ISSUE THREAD

**Issue by skybellrock** [StardewModders/mod-ideas#258]
Has it ever happened to you that youre out fishing for that one fish you need for your bundle and suddenly you catch it but your whole inventory is filled up? Has it ever happened to you that you have been forced to trash or throw an item out of your inventory to fit something you fished? Did you ever try to throw out an item with the intent of picking it up later or sorting your inventory just for it to fall into the water and dissapear? I certainly have, and whoever has experienced this might share my hatred for water. It would be great to get a mod that somehow stopped the items from falling into the water when fishing. An invisible barrier might fix it or maybe make it possible to turn while in the "swap" menu so you can throw stuff where you want to?

**Comment by KarBoy2314PL** [comment]
marking as duplicate

**Comment by EpicBellyFlop45** [comment]
Shouldn't be marked as duplicate. The newer issue was marked as duplicate instead.

**Comment by KarBoy2314PL** [comment]
this may need either:
- replacing all maps that have water tiles in them
- overriding water tile code

**Comment by Esca-MMC** [comment]
[Waterproof Items](https://github.com/Esca-MMC/WaterproofItems) is out now, which should address this. It uses a Harmony patch to prevent items from disappearing in water (and optionally teleports them to the nearest player).
