### ISSUE TITLE
Fix Hardcore mine mod

### ISSUE THREAD

**Issue by skybellrock** [StardewModders/mod-ideas#259]
There was a mod named "Hardcore mine" which made the enemies in the caves a lot more difficult, however its not updated. It would be amazing if someone could take the mod and update it to work with smapi 3.0.

**Comment by Pathoschild** [comment]
Hi! [Hardcore Mines](https://www.nexusmods.com/stardewvalley/mods/1674/) has [public source code](https://github.com/chaos234/StardewValleyMods), so it's on the list to update.  This repo is for new mod ideas; to request an update, you can [post in this forum thread](https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-3.142524/) instead.

**Comment by Pathoschild** [comment]
Apparently the author didn't add this mod to their repo, so I'll reopen it (and correct the mod list).

**Comment by MarcTowler** [comment]
Spoken to the mod owner to get permission to update and have recieved it so will give this a go

**Comment by MarcTowler** [comment]
https://www.nexusmods.com/stardewvalley/mods/6411/

v1 has been released
