### ISSUE TITLE
Double doors

### ISSUE THREAD

**Issue by Pookachutf** [StardewModders/mod-ideas#263]
The number one thing people say about my house mods is "you can look right into the bathroom while someone's peeing" y'all some pervs! but none the less they are right i need doors.. not just any doors fancy double doors that open when you click them! 

double door- door that is (at least) two tiles wide 

edit: i made a double door.. the very bottom seems to get eaten when I put it in game but ill attach it in case someone wants to do something with it for this 
![Double Doors](https://user-images.githubusercontent.com/44708241/55515082-8a407b00-561e-11e9-954f-f30dcc5a687e.png)

**Comment by danvolchek** [comment]
I've just released [Better Doors](https://www.nexusmods.com/stardewvalley/mods/3797) which lets you do exactly this! It'll also let you use custom door sprites, but they'll need to be drawn a bit differently than your sample image.

See the wiki linked on the mod page for info about how to use it :)
