### ISSUE TITLE
Plantable Coconuts to become Palm Trees

### ISSUE THREAD

**Issue by TimeWandrer** [StardewModders/mod-ideas#267]
It would be great to be able to plant coconuts that would turn into palm trees over time.

**Comment by KarBoy2314PL** [comment]
would this need overriding the coconut item? why not adding a palm tree sapling that can be crafted with a coconut instead?

also, does JSONAssets support trees?

**Comment by BlatantDecoy** [comment]
https://www.nexusmods.com/stardewvalley/mods/4096
Completed by MouseyPounds
