### ISSUE TITLE
Portable TV options (like a cell phone item you can use)

### ISSUE THREAD

**Issue by HoustoCo** [StardewModders/mod-ideas#268]
This would be super useful! Do you ever leave for the day and realize your forgot to check your luck? Or maybe you were waiting for a new Queen of Sauce episode. What if you need to check the weather but you're all the way in the mines? Just whip out a cell phone and it'll bring up the same dialogue options as a TV. Maybe it could be crafted with iridium bars and battery packs. I feel like this would add a lot to the game, and be super useful and a really easy mod to make. (Considering the TV menu already exists.)

**Comment by KeepFireFlying** [comment]
If you go with a phone, perhaps the ability to remotely talk to villagers as well?

**Comment by KarBoy2314PL** [comment]
@KeepFireFlying , [that is already done](https://www.nexusmods.com/stardewvalley/mods/2681)

**Comment by kdau** [comment]
I've been deep in the TV code recently and need some mild pixel art practice, so I think I'll take this one on. To keep the Stardew slightly-outdated-tech aesthetic I'm thinking of a [1990s portable TV look](http://tvsets.org/1990s-portable-handheld-tvs/), possibly showing programs in black and white if I can manage it.

**Comment by kdau** [comment]
It is complete: [Portable TV](https://www.nexusmods.com/stardewvalley/mods/5674)
