### ISSUE TITLE
Raphtalia Mod?

### ISSUE THREAD

**Issue by c33you** [StardewModders/mod-ideas#269]
Umm, i was looking for Raphtalia from Rise Of Sheild Hero Mods as New NPC or replacing other NPC ( i was hoping for Penny ) :3  
sorry for bad english

**Comment by TehPers** [comment]
As a texture replacement, this would be fairly easy to do with CP. A new NPC is a bit harder though. I'd label this as easy/med, depending on the approach.

If she were added as a new NPC, it'd be pretty neat if you could have her follow you, kinda like companions in Skyrim.

**Comment by Fippsie** [comment]
Hey! Even though this is almost a month old, I hope you are still interested in it.. I'm starting a project for this as of now :)

**Comment by Fippsie** [comment]
Just want to give an update! It’s going very well and I expect to be done within the upcoming week! :)

**Comment by Fippsie** [comment]
I'm done! Sorry it took me so long. :) 
https://www.nexusmods.com/stardewvalley/mods/4021/
