### ISSUE TITLE
Diablo-Like Sockets

### ISSUE THREAD

**Issue by reyak** [StardewModders/mod-ideas#271]
Simply put, all weapons and boots get a socket, much like the fishing rod has for bait. Put a vanilla gem in, and it adds stats to the item. The gem level would be based on the geode it can come from.

To avoid overly OP items, I'd limit it to one gem per item.

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/3090

This mod does that for tools, perhaps they would be interested in expanding it to weapons/boots?

**Comment by reyak** [comment]
That's actually a pretty odd, and specific selection of what gems do what... Still, it's pretty much exactly what I was looking for. Thanks! How did I not see this one, before?
