### ISSUE TITLE
Good ol' Camp Cookin

### ISSUE THREAD

**Issue by reyak** [StardewModders/mod-ideas#273]
I was thinking about using that campfire, available early game, to cook stuff like fish. There would be no recipe involved, just a GUI with one slot for raw food, another for finished cooked food, and one for logs. The created products could be very basic, like inputting any fish will result in 'grilled fish', but modify the stats of the inputted raw fish by about 10%, or so. It can be limited to anything you can normally grill, like corn or tomatoes. As basically a starter item, it should only improve the meal a small amount, and they would stack just like the original items, but with a more generic name/icon.

**Comment by Pathoschild** [comment]
See [Campfire Cooking](https://www.nexusmods.com/stardewvalley/mods/2297), which lets you cook anything over a campfire. It doesn't add a separate campfire mechanic like you describe though.

**Comment by reyak** [comment]
Yes, it does do as you say. It's a bit of a cheat, though, and it's only function is to apply the stove's GUI to other objects.
