### ISSUE TITLE
Mini Shipping Bin

### ISSUE THREAD

**Issue by masquerade908** [StardewModders/mod-ideas#274]
A placeable mini shipping bin that can be put wherever other equipment may be such as a shed that works with Automate for a full factory. No more manually checking chests each day to transfer it to the shipping bin before bed.

**Comment by KarBoy2314PL** [comment]
1. There are already placeable Shipping Boxes in SDV 1.3
2. Automate supports Shipping Boxes

marking as completed

**Comment by LeonBlade** [comment]
Is this closed if the feature isn't in the game?

**Comment by Entoarox** [comment]
Reopened, please update the first post to clarify it is for indoor needs @masquerade908

**Comment by ImJustMatt** [comment]
This is now available in vanilla SDV 1.5
