### ISSUE TITLE
ancient seed variety

### ISSUE THREAD

**Issue by Traehgniw** [StardewModders/mod-ideas#278]
would be neat if, after shipping some ancient fruit seeds, you could get like a variety of ancient seeds, including ones only originally available via mail (possibly from Gunther? like "You managed to grow the other ones. Can you make these sprout?")

bring back extinct varieties of plant :p

**Comment by TrentXV** [comment]
For what I understood you want:
new ancient crops that are accesible after you sell some ancient fruits. 

new crops can be added via json assets, the letters with Gunther sending you new types of crops can be added via content patcher...let me know if this is correct. 

If I got everything right, I should be able to do, once we get someone to make the textures.

**Comment by Traehgniw** [comment]
Yep, that's right!

**Comment by TrentXV** [comment]
Ok, can you get a list of the crops you want?
I can make the coding we will need to find an artist though

**Comment by Traehgniw** [comment]
Well the most obvious ones would be something like an Ancient Date Palm. Possibly an Ancient Nut and an Ancient Tuber plant. Ancient Olive, with a description saying that it's not actually an olive, just something that looks a lot like an olive? (based off of the Saint Helena Olive.)

Ancient Coffee, which is a small shrub with white flowers (based off of Argocoffeopsis lemblinii)

maybe some other stuff too

**Comment by TrentXV** [comment]
I will be making with the help of 6480 who is making the textures

**Comment by Traehgniw** [comment]
thanks!

**Comment by TrentXV** [comment]
Here is what we came up with:

Ancient Tuber - Ship X amount of Ancient fruits and Gunther sends you 10 seeds via mail
Ancient Flower - Ship X amount of Ancient Tuber's and Gunther sends you 10 seeds via mail

Ancient Coffee - obtain from mummies (rare drop)
Ancient Nut - after CC completion you receive a misterious gift with the seed
Ancient Fern after getting 10 hearts with all citizens (not including custom ones and bachellors) you receive a misterious gift
Ancient Olives after you've shipped at least one of each Ancient Crop

You cannot purchase them, but you can place them in the Seed Maker
The letters will state that

The seeds received by Gunther are one time harvest
The others regrow

I will prepare a spreadsheet with the data of growth and other stuff

**Comment by TrentXV** [comment]
https://docs.google.com/spreadsheets/d/1l43AJhrQ5JXjscC4a2ifDUBOUvgzldeH6YqPoCjJJAg/edit?usp=sharing

**Comment by Traehgniw** [comment]
good!!! good.

**Comment by TrentXV** [comment]
Alright I will begin the test, I added a personal touch, so once you shipped at least 5 of each ancient crop you will get a stardrop via mail.

**Comment by TrentXV** [comment]
Mod is finished we are beta testing it atm. Should be released next week

**Comment by Traehgniw** [comment]
huzzah!!!

**Comment by TrentXV** [comment]
https://www.nexusmods.com/stardewvalley/mods/4472
