### ISSUE TITLE
pufferchicks for BFAV

### ISSUE THREAD

**Issue by Traehgniw** [StardewModders/mod-ideas#283]
cause theyre great but so are fancy chickens

...also if they're added as a new animal species then they can have different products or something

**Comment by KarBoy2314PL** [comment]
@Pathoschild add that to your Pufferchick collection m8 xd

**Comment by mytigio** [comment]
I think this mod does covers this request? https://www.nexusmods.com/stardewvalley/mods/6162?tab=description
