### ISSUE TITLE
[Event] Community Cleanup

### ISSUE THREAD

**Issue by KeepFireFlying** [StardewModders/mod-ideas#284]
I know there are mods out there to clean up the beach and the area around the trailer, but it would be cool to have an event where the community works together to pick up all that litter.

**Comment by KarBoy2314PL** [comment]
#trashtag

try suggesting that to Stardew Valley Expanded, this seems like something that would fit there

**Comment by Pathoschild** [comment]
This could be done with just Content Patcher to create a custom event and conditional map patches.

**Comment by KeepFireFlying** [comment]
@KarBoy2314PL I'd prefer if it was separate from SVE since not everyone wants to use that. I do plan on getting into it eventually, but I want to save it for more of an endgame thing.

@Pathoschild I didn't realize CP handled events. Hopefully this will be relatively straightforward for someone. I'm not super confident in my writing.

**Comment by Entoarox** [comment]
@KeepFireFlying Events are data scripted into xnb files, so yes, CP can let you add events and use CP tokens to have actions occur based upon those events.

**Comment by minervamaga** [comment]
Deprecated by SDV 1.4
