### ISSUE TITLE
Bulk buying mixed seeds from krobus

### ISSUE THREAD

**Issue by Traehgniw** [StardewModders/mod-ideas#285]
Without having tp 9pen and close the ahop menu every 10 seeds cause thats a pain and some of us want ro plant the immersive farm 2 remastered farm qlmost evtirel6 with mixed seeds

Hopedully thisbis inderstabdable phone keyboard is bad keyboard

**Comment by Traehgniw** [comment]
translation from typoland in case it's needed/wanted:
"Without having to open and close the shop menu every 10 seeds, because that's a pain and some of us want to plant the immersive farm 2 remastered farm almost entirely with mixed seeds."

and then complaining about the phone keyboard

**Comment by KarBoy2314PL** [comment]
add Geodes on top of that also thx

**Comment by Pathoschild** [comment]
Editing shop stock is pretty easy to do, just need to edit the shop menu data after it's opened.

**Comment by Annosz** [comment]
Hi guys! I created a mod where you can configure each item's quantity in Krobus's shop - it can take care of the issue with Mixed Seed and Omni Geodes. You can find it on the [Nexus](https://www.nexusmods.com/stardewvalley/mods/5993), and you can watch the source code on [Github](https://github.com/Annosz/StardewValleyModding/tree/master/StardewValleyMods/SleeplessFisherman).
