### ISSUE TITLE
More slime craftings.

### ISSUE THREAD

**Issue by Lysio6** [StardewModders/mod-ideas#286]
So i basically thought that it would be cool if you could make some floors Made of slime, so you can slow down some Monsters significantly, if they step on it but it also slows down the Player. It could Help in skull cavern if there are too many Monsters. Also maybe you can add some Kind of potion, that makes enemies bouncing back, if they attacked you.

**Comment by Lysio6** [comment]
And also in general more things you can craft with slime

**Comment by KarBoy2314PL** [comment]
please split these suggestions into multiple issues

**Comment by Entoarox** [comment]
@Lysio6 Your idea is not detailed enough, you are giving possible uses for crafting with slime yes, but these are very spread out and do not actually *require* slime, please split it into "Enemy slowing floor" and "Enemy bounce buff" ideas. :)
