### ISSUE TITLE
Large Mayo/Cheese

### ISSUE THREAD

**Issue by Kajin-Strife** [StardewModders/mod-ideas#288]
The idea is pretty basic (I think? I don't actually know how complicated this will end up being). It involves creating three new images for a Large Mayo, Large Cheese, and Large Goat Cheese. Then rework the processing system so that when a large variety of egg or milk is used, instead of popping out a gold star quality it instead pops out a large item of the artisan good.

Then work the system further so that the quality of the end product is tied into the quality of starting product. A silver star egg results in a silver star mayo, while an iridium large goat milk results in an iridium quality large goat cheese.

**Comment by KarBoy2314PL** [comment]
JSONAssets?

**Comment by Kajin-Strife** [comment]
I don't know. I've only just gotten into modding Stardew, I have no idea whatsoever what's going on.

**Comment by Traehgniw** [comment]
JsonAssets is a mod that lets you add items eg new crops, or new machine goods

**Comment by TrentXV** [comment]
This would need to be done on CFR

**Comment by BlatantDecoy** [comment]
JA:
Large Mayo
Large Cheese
Large Goat Cheese

CFR:
    Large Mayonnaise Machine:
    Large Egg > Large Mayo

    Large Cheese Press:
    Large Milk > Large Cheese
    Large Goat Milk > Large Goat Cheese

    Large Cheese Cask*:
    Large Cheese > Upgrade Quality
    Large Goat Cheese > Upgrade Quality

*Note that the way CFR works, you would need to remove and re-add the cheese between each "upgrade quality" step.

**Comment by zeronacer** [comment]
Done as my first mod project! Thanks for the idea.
https://www.nexusmods.com/stardewvalley/mods/5870
