### ISSUE TITLE
Mod config record 

### ISSUE THREAD

**Issue by thomwblair** [StardewModders/mod-ideas#291]
I just thought of something that’d be a real boon to mod users: a mod that records all your config files and keeps a copy with your save game so that if you have to do a clean install, it’d keep all your changes/config preferences and patch them in for you once you did the clean install. Because right now I’m going to either have to do a clean install manually of 80+ mods or just give up and play something else.

**Comment by thomwblair** [comment]
Also neat would be if it kept the zip files of all your mods somewhere so that if you need to do a clean install, it’d do it for you, saving you from hunting them all down again manually and downloading them again. That’d be an incredible time saver!

**Comment by thomwblair** [comment]
The reason I’m having to consider a clean install is because I messed up SDVE installation (I think) and now several parts of the game aren’t working correctly, but SMAPI log shows no errors and nobody in the forums knows what the answer is.

**Comment by Entoarox** [comment]
I am sorry, but this sounds more like the task of a mod manager or backup script then a mod.

I get your feelings, but these suggestions are meant to be about mods for SDV, not external tools (Which this would work best as)
