### ISSUE TITLE
Gaining energy from being social?

### ISSUE THREAD

**Issue by Wackyerror** [StardewModders/mod-ideas#293]
The major problem I'm having with Stardew Valley at the moment is that so much of the character interactions require that I talk to the characters, but there's rarely ever an incentive to be communicative. 
What I would love is a mod that allows you to regain energy by talking to characters- Maybe something flat, like +15 energy, or scaling based on the number of hearts you have with them. Maybe provide a bigger bonus for 
I'm not sure how complicated. I'm not certain how viable it would be to implement, but it seems relatively simple to implement. I know one method would be to integrate it into *every script in the game,* but that isn't really viable for modded dialogue.

**Comment by ATMCrocker** [comment]
I have a mod that does the majority of this already. However, currently, it only applies to NPCs with 10 hearts. I'm currently adding a config option to allow this to work with any heart level.

**Comment by EpicBellyFlop45** [comment]
https://www.nexusmods.com/stardewvalley/mods/3605?tab=files V1.0.5 has this update
