### ISSUE TITLE
All type of vegetables, herbs, flower and fruit trees

### ISSUE THREAD

**Issue by RainneyUchiha** [StardewModders/mod-ideas#295]
Can someone make one for me for the latest version of stardew valley games world... i really need it badly

**Comment by Entoarox** [comment]
Not actually a suggestion for a new mod but a request for a existing mod to be updated, not relevant to this github.

Please go to the relevant location to make a update request, this place is not it.

**Comment by Pathoschild** [comment]
Adding _all_ types of plant isn't really feasible, but [Project Populate Json Assets](https://www.nexusmods.com/stardewvalley/mods/1935) adds a lot.
