### ISSUE TITLE
The farm and the villager mod is expanding and where more new villager are moving in and we can visit other town and city

### ISSUE THREAD

**Issue by RainneyUchiha** [StardewModders/mod-ideas#297]
I am request this mod to be make as well... so we can have more married canned to be pick and i wanted the other single villager also getting married with the one we didnt choice or pick... please add naruto, sasuke, hinata, ino, sai, daisuke, yomato, taichi, ryo and many more

**Comment by Entoarox** [comment]
Please rewrite your suggestion to be more clear, at this time it is more of a run-on of rambled half-ideas.

Closing this pending a rewrite, at which point it can be reopened.

**Comment by Pathoschild** [comment]
If I understand correctly, the request is...
* Expand the town area (e.g. [Stardew Valley Expanded](https://www.nexusmods.com/stardewvalley/mods/3753)).
* Add new custom NPCs.
* Add other towns/cities that can be visited by the player.
* Once you get married, other eligible villagers marry each other automatically.

This should be split into multiple ideas though.
