### ISSUE TITLE
Expanding farm land where we and other 3 player player have their own area of the farm was divide 

### ISSUE THREAD

**Issue by RainneyUchiha** [StardewModders/mod-ideas#298]
Where each of all player can expanding the house and handle the farms, as well risen the child to their teenager form so they can help out the farm and build their own family, where in the village or town of our own have a school and teacher to teach the kids

**Comment by Entoarox** [comment]
One of these suggestions is to come in the next SDV update and thus considered already implemented.

Please separate the remainder of your suggestions into their own issues, every suggestion needs its own issue so that they can be accepted and implemented on their own merit.
