### ISSUE TITLE
Sort by... option for inventory management

### ISSUE THREAD

**Issue by thomwblair** [StardewModders/mod-ideas#300]
I wonder if a Sort By.... dropdown box/option would be good for inventory management? So that when I've got tons of fruits and veggies and I'm trying to figure out which to load into kegs and stuff I can figure out quickly which is best?

**Comment by BlatantDecoy** [comment]
See: https://www.nexusmods.com/stardewvalley/mods/1992
by Jower.

You can create a custom "sort by" but as far as I'm aware you can't have multiple different ones and select them via drop down.
