### ISSUE TITLE
More ways of obtaining battery packs

### ISSUE THREAD

**Issue by OfficialRenny** [StardewModders/mod-ideas#301]
Currently playing around with the Industrialisation mod which introduces a lot of battery pack powered machines for stuff like generating ores or electric furnaces.

Would like to have a way of producing even more battery packs, other than using lightning rods (which aren't really consistent). For example, using solar panels or wind turbines that passively generate battery packs.

**Comment by Fippsie** [comment]
I have some ideas for this and want to play around with it, but don't want to promise anything :)

**Comment by OfficialRenny** [comment]
Not so long after making this post I found out about CFR, so currently playing around with it. Made Solar Panels and Wind Turbines so far which work quite well. Just trying to figure out balancing (and maybe get some help with the tilesheets as i'm not good with pixel art at all)

**Comment by minervamaga** [comment]
A solar generator was added to Industrialization recently, closing this issue!

https://www.nexusmods.com/stardewvalley/mods/3034
