### ISSUE TITLE
Foundry

### ISSUE THREAD

**Issue by EmperorMozzy** [StardewModders/mod-ideas#305]
Furnaces are great and all, but it can be a pain to constantly reload them with ores and coal to get your ingots. An idea I had is to add a build-able (via Robin) foundry that allows as many ores as your want loaded into it that constantly churns out bars (akin to the mill).

**Comment by EpicBellyFlop45** [comment]
What you could is download the mod 'Automate' (https://www.nexusmods.com/stardewvalley/mods/1063). That allows you to put a chest next to the furnace and it will pull coal and the ores whenever there is enough of both. You can also use paths as 'pipes' so to speak, so the chest is far away from the furnaces. This can also pull ingots out of the furnaces.

**Comment by EmperorMozzy** [comment]
Automate is great and all, but my wife hates it. Plus, if you only wish for one set of chest systems to be automated (in my case, ores to bars) you then have to be meticulously careful not to place chests next to anything else it would otherwise automate, which undermines good housekeeping and general feng shui of the entire farm.

**Comment by BlatantDecoy** [comment]
This would be a good mod akin to the mill.

This is an alternative: https://www.nexusmods.com/stardewvalley/mods/2321

**Comment by Traktori7** [comment]
Here's my take on it: https://www.nexusmods.com/stardewvalley/mods/5568
