### ISSUE TITLE
Yamper

### ISSUE THREAD

**Issue by yamper** [StardewModders/mod-ideas#306]
could someone make a mod that replaces the dog with yamper from pokemon sword and shield? heres a picture
![Yamper](https://user-images.githubusercontent.com/51734752/59326382-419ae300-8c9b-11e9-8f44-ebbe3581c993.png)

**Comment by AlexisBloodwood** [comment]
I'll be tackling this one as soon as the rest of my pc parts come in! Can't wait to see this happy pup come to life ^-^

**Comment by AlexisBloodwood** [comment]
I finished this one a lot sooner than I thought I would! The pup has been uploaded [here!](https://www.nexusmods.com/stardewvalley/mods/6824/)

**Comment by Lumisteria** [comment]
> I finished this one a lot sooner than I thought I would! The pup has been uploaded [here!](https://www.nexusmods.com/stardewvalley/mods/6824/)
Great ! I hope the person who requested it will see it :)
