### ISSUE TITLE
Farmers Market Style Furniture Pack

### ISSUE THREAD

**Issue by Blossom513** [StardewModders/mod-ideas#310]
I would love to be able to have a custom set of furniture (to be used outside for example with Furniture Anywhere) that looks like a farmers market display or summer fair so i could display all the new Artisan valley items in a fun way. I've thought about pulling some of the creative from inside pierre's shop (the barrels/boxes of fruit) but it would be neat to have barrels/boxes of various tree fruit, artisan products, or signs/flags reminiscent of a agricultural fair/state fair or farmers market.

**Comment by Fippsie** [comment]
Hey this is a great idea! I made an arch using the festival stand, is that the style you are looking for?
https://www.nexusmods.com/stardewvalley/mods/4098

**Comment by Blossom513** [comment]
Hi Fippsie! Yes actually I had been mulling this idea for awhile and then I saw your arch and it prompted me to post here with the suggestion! I love that arch and I was definitely going to use it to make my own little farmers' market area with custom furniture, but it'd be awesome if there were more components to work with like fruit/veggie stands barrels etc. :)

**Comment by Lumisteria** [comment]
I'll try doing some furnitures on this theme.

**Comment by Lumisteria** [comment]
And here is my version of the mod :

https://www.nexusmods.com/stardewvalley/mods/4462

I hope you'll like it. The stands are structures (so you need materials to build them).

**Comment by Blossom513** [comment]
@Lumisteria this is amazing!! Thank you so much <3 <3
