### ISSUE TITLE
More Space for hill tops, wildness, forest, riverland

### ISSUE THREAD

**Issue by RainneyUchiha** [StardewModders/mod-ideas#313]
Where the player house are have a lots of space and area to grow it.. when play with other player they also have their own space land and place to grow it...

**Comment by Pookachutf** [comment]
I'll start working on this today

**Comment by Pookachutf** [comment]
update: in the testing phase now

**Comment by Pookachutf** [comment]
Standard farm is released https://www.nexusmods.com/stardewvalley/mods/4294
