### ISSUE TITLE
New rooms - with the possibility to decorate walls

### ISSUE THREAD

**Issue by Rappeldrache** [StardewModders/mod-ideas#32]
A mod that makes it possible to create new indoor rooms for the farmhouse. Also, make it possible to decorate the walls and floors.

Sorry for my english. :(

**Comment by Entoarox** [comment]
Marked as hard due to the "possible to decorate walls and floors" requirements, as vanilla coding is in no way designed for this.

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/3731
