### ISSUE TITLE
Fetch & Pets

### ISSUE THREAD

**Issue by vadie1** [StardewModders/mod-ideas#322]
Is there any way to make a mod that would let you play fetch with your pets? Kind of like how in the Harvest Moon games you can throw a ball or bone and your dog or cat will go fetch it, then bring it back to you. Doing this like once or twice a day would raise affection with your pet.

Little interactions with your pets like this, I think, would make them not only more enjoyable to have around (and not as easily forgettable), but would help players be better immersed in the game.

Also, and these are just extra interactions, but maybe having more interactions with the pets similar to Harvest Moon, in general, would be nice? Maybe like picking up the pets as a way to pet them, or if you hit them with a tool by accident, you lose affection with your pet. But these are only extra ideas that I thought I'd mention after discussing with people on the discord.

Thank you to anyone who could maybe do this mod~!

**Comment by jahangmar** [comment]
I was thinking about re-implementing [this mod](https://community.playstarbound.com/threads/smapi-consilliums-pet-enhancement-mod.114314/). My plan is to let your pet follow you around and add silly behavior as chasing birds. My real-life cat attacks the holes I made for the onions to be planted in. So I could add something similar.
I just checked how hard it would be to implement your fetch idea and I think I can do it. As soon as I have a working prototype, I will give you an update.

**Comment by jahangmar** [comment]
I'm working on this. I will re-implement "Pet Enhancement" with additional features such as
* pets follow you on different maps and not only on the farm
* you can play fetch with your pet
* your pet reacts to being hit by a tool or being watered
* additional pet-like behaviour.

**Comment by jahangmar** [comment]
https://www.nexusmods.com/stardewvalley/mods/4232/
