### ISSUE TITLE
New Events/Festivals Involving Pet/Horse/Barn Animals

### ISSUE THREAD

**Issue by TimeWandrer** [StardewModders/mod-ideas#323]
Would love to see a few new events or festivals that involved the player's pet/house/animals. 

Maybe a horse race, pet trick competition, or a way for the animals to be judged...

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/1538/

Animal Husbandry just updated with new animal contests.  I'll mark this complete for now!
