### ISSUE TITLE
Better/Improved Tracker Skill

### ISSUE THREAD

**Issue by Capricus02** [StardewModders/mod-ideas#326]
Currently, the Tracker skill for foraging consists of tiny yellow arrows along the edge of the screen which can be hard to see and sometimes difficult to navigate while walking/running through a forest. 

Request: A better/improved tracker set with customizable arrows (both in color and size).

**Comment by jahangmar** [comment]
I not really interested in doing this right now but I checked how one would implement this so maybe this info is useful for someone:

To change the color of the arrows:
Arrow sprite can be found in LooseSprites/Cursors.xnb at (412, 495, 5, 4).
To change the size of the arrows:
The code drawing the arrows is located in Game1.drawHUD() where
`player.professions.Contains (17)` is checked.

**Comment by Slamerz** [comment]
I'll take a wack at it. Interested in playing around with original mods and seems like a good starting point.

**Comment by Esca-MMC** [comment]
Custom Tracker coincidentally fulfills this: https://github.com/Esca-MMC/CustomTracker
