### ISSUE TITLE
Keep villager houses open longer in summer

### ISSUE THREAD

**Issue by Lumisteria** [StardewModders/mod-ideas#327]
The idea is that, in summer, villagers houses will be opened for a longer time, since you usually have longer evening and people have more time with sunlight to enjoy. It will make the village a bit more lively.
(It will probably require to change some messages about opening hours and stuff like this).

**Comment by minervamaga** [comment]
This should be easily doable with map editing.  I may take this one!

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/4248/

**Comment by Lumisteria** [comment]
Thanks !
