### ISSUE TITLE
Fixing Fire on Large Farms

### ISSUE THREAD

**Issue by DoctorDDub** [StardewModders/mod-ideas#329]
On larger farms, the fire animation of braziers, campfires, torches, etc. is messed up on the right side of the map. The flame appears behind the item instead of in front of or on top of it. The issue happens at a certain x coordinate and every tile to the right of it. Moving up and down the y axis of the farm seems to have no effect on it. I've tested this on several larger farms and the issue persists.  Feel free to DM me on discord @ DoctorDDub#1909 if you need any more details!

**Comment by Entoarox** [comment]
This is a bug, please report it in the appropriate place for reporting bugs in SDV.
