### ISSUE TITLE
Legend of Zelda inspired horse summon

### ISSUE THREAD

**Issue by freshfromthedirt** [StardewModders/mod-ideas#330]
Something by way of playing a short song to spawn your horse wherever you are; ideally nothing you would have to carry.

**Comment by jahangmar** [comment]
Is [this](https://www.nexusmods.com/stardewvalley/mods/1131) what you are searching for?
I'm not using it and there seem to be issues with this mod but it does what you ask for except the part about the song.

**Comment by Pathoschild** [comment]
I'll mark this complete since it already exists. It does play a whistle sound too.
