### ISSUE TITLE
Blue Eggs for Blue Chickens

### ISSUE THREAD

**Issue by lawnflamingo** [StardewModders/mod-ideas#331]
Every other bird has their own type of egg, while blue chickens for some reason just lay white eggs. I would love a mod that gives blue chickens their own Blue Egg and Large Blue Egg. It would (hopefully?) be easy to make too!

**Comment by TrentXV** [comment]
It is very easy to make, however Blue Chicken egg would not work in standard Mayo Machine also, won't be possible in the incubator as far as I know....let me know if that is ok for you and I can make the mod.

**Comment by Balmmaker** [comment]
This exists on Nexusmods

**Comment by Pathoschild** [comment]
@Balmmaker Can you link to the mod?

**Comment by Balmmaker** [comment]
https://www.nexusmods.com/stardewvalley/mods/5875
