### ISSUE TITLE
Ocean Fish in Forest of Stardew Valley: Reimagined

### ISSUE THREAD

**Issue by StopTakingAllTheNames** [StardewModders/mod-ideas#333]
The part beneath the waterfall is actually the sea already, would be great if we could catch ocean fish in it since the sea portion is now accessible via the mod.

It would also make it great for ocean fishing on festival days involving the beach, especially the moonlight jellies festival and the winter market. For newbies it also means fishing in the sea is possible before constructing the water obelisk.

Inspiration: [Small Beach Farm](https://www.nexusmods.com/stardewvalley/mods/3750)

**Comment by Pathoschild** [comment]
Hi! Unfortunately this repo is for new-mod ideas, rather than improvements to existing mods. I suggest posting your idea to the [Stardew Valley Reimagined](https://www.nexusmods.com/stardewvalley/mods/4119) page instead.
