### ISSUE TITLE
Trash removal + renovation

### ISSUE THREAD

**Issue by brassoctopi** [StardewModders/mod-ideas#340]
I'm frustrated by all the trash laying around Pelican Town, as well as the broken fences. There used to be a mod that could help fix this (Cleanup Crew), but it hasn't been updated since 2017 and used ALL. That mod had you use money to clean up the trash and a matching fence style to fix fences; I'd like something like that, but even something that just removes all of it from the start would be good too. I just hate running into the immovable piles on the ground.

**Comment by BlatantDecoy** [comment]
This request seems majority obsolete with Stardew Valley 1.4 "Added Trash Bear to clean up trash around town in year 3+."

**Comment by minervamaga** [comment]
Indeed it is!  Closing
