### ISSUE TITLE
more babies

### ISSUE THREAD

**Issue by qkrtjs19912** [StardewModders/mod-ideas#341]
The most unsatisfactory thing in my marriage while playing the game was the Dialogue problem, which is that even though I made the mode myself, the pattern is small. Above all, only two children were allowed to have.
I think it would be great if we could extend it in mode. Like 'more pets mod'!

**Comment by Entoarox** [comment]
Please reformulate your request, while I *think* I know what you are asking, I am not *certain* of it.

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/4515
