### ISSUE TITLE
Level cap adjustment

### ISSUE THREAD

**Issue by tristanschm** [StardewModders/mod-ideas#343]
Hello.

I wanted to ask if somebody would want to make a mod that alters the experience level caps? 
I play with additional speed and am leveling up way too fast. Would love to change the setting to make it harder.

So instead of :
Lvl Total Experience
1 100
2 380
3 770
4 1300
5 2150
Lvl Total Experience
6 3300
7 4800
8 6900
9 10000
10 15000

you have something like this:

Lvl Total Experience
1 100
2 500
3 1500
4 3000
5 5000
Lvl Total Experience
6 9000
7 12000
8 18000
9 25000
10 40000

**Comment by jahangmar** [comment]
I will do this. There will be a configuration file where you can configure the leveling list for each skill. I might use your values as a default. I'm also thinking of implementing optional features similar to those proposed in #118 .

**Comment by jahangmar** [comment]
https://www.nexusmods.com/stardewvalley/mods/4689/
I modified your idea but the result should be the same.
Does this do what you want?

I modified the idea because the configuration is much easier and for technical reasons.

**Comment by KarBoy2314PL** [comment]
closing as this is completed
