### ISSUE TITLE
Automatic deletion of specific items in your inventory

### ISSUE THREAD

**Issue by KLaurence** [StardewModders/mod-ideas#344]
I think this mod's "list of items that should be automatically deleted" should be customized with a config file or a menu in-game. I also think that it might be helpful that a bottom-left corner pop-up should show when an item is deleted, like "Lead Rod has been automatically deleted" or something else.

**Comment by CompSciLauren** [comment]
A mod called [AutoTrash](https://www.nexusmods.com/stardewvalley/mods/4924) has just been released which accomplishes this.
