### ISSUE TITLE
Kiss your boyfriend/girlfriend mod!

### ISSUE THREAD

**Issue by HoneyBbunches** [StardewModders/mod-ideas#362]
I think it's a shame that we only (maybe) kiss the NPC we're dating in a cutscene and then have to wait until marriage. 
So I had the idea for a mod that would let you kiss your girlfriend/boyfriend without having to marry them first!
That way the dating period would be more fulfilling, at least I personally think so.

In my head this would become available (obviously) after we have given the NPC a bouquet to officially start dating. 
Maybe it could also have the added option of configuring when we'd be able to kiss them (for example immediately, after reaching 9 or 10 hearts or when having seen the NPCs 10 heart event)! 
I don't know how hard it would be to make this mod, since the NPC has a schedule when they're not moved in with you, but hopefully it is still doable! ♥

Thank you very much!!

**Comment by Lumisteria** [comment]
https://www.nexusmods.com/stardewvalley/mods/4664
Someone made this mod.
