### ISSUE TITLE
Better Iridium Meteorite

### ISSUE THREAD

**Issue by JESSEQUEST** [StardewModders/mod-ideas#365]
Didn't even realize I would post this until I just did this, but I finally got that dang meteorite off of my property. I was expecting something sizable from it... nothing ginormous or whatever, but something more than what I got. What I got was -
- 11 stones
- 3 coal
- 3 normal geodes
- And finally, 6 iridium ore (or, 1 stinkin' iridium bar)

I'm on year 2 in Fall, and at this point, the first three I could get in probably 1 in game hour of game play. As for the iridium, that would probably only take me 1/4th to 1/2 of an in game day to get. 

So... what gives? Definitely not this dang meteorite that was taking up this room on my farm. Now I'm not sure if this is an event that can happen multiple times or whatever, but either way, I think the loot isn't substantial enough for the event.

My suggestions for a mod to make this better--
For the items:
- 100-200 stones
- 25-50 coal
- Between 10 and 20 geodes of all types
- And lastly, the main event, 60-120 iridium

Optional additions could include:
- Some sort of unique weapon or weapon pieces (if there are multiple possible, needed to create a big bad weapon or item after maybe destroying 3 or 5 of these. Heck, maybe make this mod have a few different epic items that can be made with these parts so the players have a choice what to save up for)
- Extra benefits for an easier game-- a couple spaces from the meteorite, crops grow substantially faster and have higher qualities.
- Extra challenge for a more 'realistic' game-- the meteorite would actually leave a dirt trail/destroy a line of tiles just above, below, or to the side of it. However, this could unearth items below it like some artifacts, geodes, seeds, or cave carrots below it. It may even destroy trees and rock that were in the way which can be collected as materials.

Thank you for reading!

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/5096/
