### ISSUE TITLE
Expanded Monsters Kill List (Combat Mods Suite Idea Series, #2)

### ISSUE THREAD

**Issue by JESSEQUEST** [StardewModders/mod-ideas#370]
This one is short, sweet, and easy to understand as an idea... but I don't know how doable it is. 

An expanded monsters kill list in the adventurers guild would keep players hunting for longer. This would add more monsters to slay on Gil's list, as well as more/better prizes for slaying said monsters. This could include not just the ones that aren't included, but the types of each monster (green/blue slimes, frost/fire bats, etc.)

It's as simple as that. Don't know if it is wanted at all, but it would keep you in the mines looking to kill more monsters to make a quota fast enough. Actually, I just had an expanded idea off of how the last sentence was worded.

It might be cool if after you completed the list or after a certain amount of time (say, an in game month or week) to meet a quota. And the better you do, the better large scale prizes you can get.

What do you all think? Thanks for reading! :)

**Comment by minervamaga** [comment]
That sounds like this mod: https://www.nexusmods.com/stardewvalley/mods/2301

**Comment by JESSEQUEST** [comment]
Oh. Oof. Okay. Yeah that looks good. Imma close this issue.
