### ISSUE TITLE
Craftable Holes

### ISSUE THREAD

**Issue by pcsbx** [StardewModders/mod-ideas#38]
The Beatles did it so why not SDV?

Craft Holes to carry in your pockets for that Skull Cave excursion.

Your benefactor and peculiar fan Mr. Qi sends you the recipe in mail after you've reached lvl 50 in Skull Cave.

Possible ingredients:
* a bunch of Void Essence (for reasons that hopefully are self-evident)
* a bunch of stone (for stability)
* Orpriment (for penetration)
* Truffle Oil (for lubrication... better not ask)

**Comment by S1mmyy** [comment]
Attempting to work on making this.

**Comment by S1mmyy** [comment]
Mod(s) finished.
[https://www.nexusmods.com/stardewvalley/mods/6120](https://www.nexusmods.com/stardewvalley/mods/6120)
