### ISSUE TITLE
JA-like spritesheet limit breaking for farmer skintones?

### ISSUE THREAD

**Issue by Traehgniw** [StardewModders/mod-ideas#380]
There is an old and no-longer-updated mod I quite liked, Anthro Farmers Continued, which had a very long list of skintones. With the release of Stardew Valley 1.3, it had to cut down the amount of skintones massively.

With the recent release of JsonAssets that removed the crop and tree spritesheet limit, I've found myself wondering if a mod couldn't do a similar thing with skintones and allow people to add many new skintones without removing the existing ones.

**Comment by minervamaga** [comment]
[Get Glam](https://www.nexusmods.com/stardewvalley/mods/5044) allows up to 4096 skin tones currently and that number could be increased if needed.  Marking closed.
