### ISSUE TITLE
Heartbeat - Starbound to Stardew conversion

### ISSUE THREAD

**Issue by Minakie** [StardewModders/mod-ideas#386]
Hey guys.

I keep dying in the mines because I just forget to check my health bar. So I thought maybe someone could convert Heartbeat (https://steamcommunity.com/sharedfiles/filedetails/?id=1296666565) from Starbound to Stardew. It's basically a mod that plays a heartbeat warning sound once your health drops below a certain (configurable) percentage.

**Comment by embolden** [comment]
I made this for you. https://www.nexusmods.com/stardewvalley/mods/5941/

Source: https://github.com/embolden/Heartbeat/tree/master
