### ISSUE TITLE
More shop items

### ISSUE THREAD

**Issue by TheOnlyParzival** [StardewModders/mod-ideas#387]
A mod that could let u buy items like cheese presses, kegs and mayo makers would be awesome and would really help out and to balance it a little you can only buy them in year 2 and up

**Comment by minervamaga** [comment]
Could be pretty easily done with TMXL custom shops and event conditions.

**Comment by LenneDalben** [comment]
I'm working on this, using Shop Tile Framework (STF).

**Comment by TheOnlyParzival** [comment]
Thats awesome, Its crazy to think your working on this mod I thought of
almost a year after I submitted it!

**Comment by LenneDalben** [comment]
On Nexus Mods, I've published [(STF) Artisan Equipment for Sale](https://www.nexusmods.com/stardewvalley/mods/6354).
