### ISSUE TITLE
Seed Sales Tweak

### ISSUE THREAD

**Issue by JESSEQUEST** [StardewModders/mod-ideas#398]
This is an idea I had for a mod that makes seeds for the next season available on the 28th of each month. Now, you won't have to stock up on the seeds prior or run over to his shop and wait until 9am to start shopping and get back at 9:40am to start farming! You can simply buy them the day prior, wake up, and get to plotting your new farm layout!

**Comment by LenneDalben** [comment]
Completed by [Pierre Plans Ahead](https://www.nexusmods.com/stardewvalley/mods/6272) and [Joja Plans Ahead](https://www.nexusmods.com/stardewvalley/mods/6273) on nexusmods.
