### ISSUE TITLE
Sundrop City seeking new team members!

### ISSUE THREAD

**Issue by Froststar11** [StardewModders/mod-ideas#399]
Sundrop City is a mod that adds an entire new big city modeled loosely after San Fransisco, USA to the game. We're already pretty far in the development process, and are seeking to expand the team with more artists, map modders, coders, and more to help us keep going! The mod has been on hiatus for a little while due to the admins dealing with real life issues, and we've lost some team members along the way due to real life happenings, but it's time to get things moving again! You don't have to be available 24/7; any time you could dedicate to the mod would help immensely!

If you have any questions ping me (Froststar11) on discord in #modding.

**Comment by minervamaga** [comment]
Merged with main Sundrop City issue
