### ISSUE TITLE
Variety of Hijabs as Hairs

### ISSUE THREAD

**Issue by UrCanSwim** [StardewModders/mod-ideas#404]
With the new 1.4 update, they added in turbans that you can buy and wear and it made me think "What about hijabs?" in-game. There could be a variety of styles for the hijabs, from simple styles to more complex styles, and hence them being in the hair category they can be any color the player wants.

**Comment by AndyAllanPoe** [comment]
I can't code but I can draw,
![pink hijab with golden clip FRONT](https://user-images.githubusercontent.com/61992831/85965945-3a607900-b973-11ea-883e-98c504a2bbd8.png)
[pink hijab with golden clip FRONT.zip](https://github.com/StardewModders/mod-ideas/files/4843413/pink.hijab.with.golden.clip.FRONT.zip)

**Comment by Traehgniw** [comment]
These could also go in Get Glam

**Comment by AndyAllanPoe** [comment]
Feel free to use just credit

**Comment by UrCanSwim** [comment]
oh sorry for the late respone! That hijab looks cute!! I don't know how to code either so idk how to get it in game ):

**Comment by minervamaga** [comment]
https://www.nexusmods.com/stardewvalley/mods/6164
