### ISSUE TITLE
Random Gift Tastes

### ISSUE THREAD

**Issue by karekanol13** [StardewModders/mod-ideas#405]
The current Random Tastes mod doesn't allow for a lot of customizability, and it's possible that some NPCs can have non-giftable items as their favorite gifts which can be very disappointing when it's already hard enough figuring out what they do like! If there was some sort of Content Pack way to randomize the gift tastes in a proper way, I hope someone can figure it out!

**Comment by Entoarox** [comment]
This should be taken up with the author of the mod in question, as NPC's wanting things that cannot be given to them is essentially a bug that needs fixing.

Content packs to control it are again, things you should suggest directory to the mod author rather then here - this is for suggesting new mods, not modifications to existing ones.
