### ISSUE TITLE
Staring Contest With Rocks

### ISSUE THREAD

**Issue by JESSEQUEST** [StardewModders/mod-ideas#410]
If you didn't know by now, this mod is humorous in nature. But it could serve some practical use, I suppose.

Make rocks and precious gem deposits buckle under your intimidating glare. Standing facing any of these without moving for a time will destroy the object, leaving materials behind that would have been there if you had mined it. The tougher they are, the harder they are to intimidate into exploding-- so it takes more time.

Proposed Times In Game Time:
Ice Shards - 10 minutes
Rocks - 30 minutes
Metal Deposits - 50 minutes
Precious Gem Deposits - 1 hour 20 minutes
Giant Boulder - 2 hours
Iridium Deposit - 3 hours

**Comment by MarcTowler** [comment]
I am happy to give this one a go

**Comment by MarcTowler** [comment]
This is now complete https://www.nexusmods.com/stardewvalley/mods/6376
