### ISSUE TITLE
Less Work On Weekends

### ISSUE THREAD

**Issue by JESSEQUEST** [StardewModders/mod-ideas#412]
Working at Joja was the worst, but at least you still had weekends free! Don't we all deserve a little time off? Well this mod idea would solve that.

Through some miracle of Yoba, your garden is now watered fully at the beginning of each Saturday and Sunday! This opens up some time for you to do whatever you want to rest during the weekends!

Pets could also be happy and automatically set to fed! This would just leave harvesting to do, and that's pretty much it.

Take your weekends of energy to - fish, go adventuring in the forest, cave or desert, spend the day with villagers, or even do a bit of redecorating!

**Comment by Entoarox** [comment]
The player is essentially self-employed, so if you want your weekends off you should schedule things so you can have that free time, and accept the fact that you'll earn less money as a result (After all, Joja only paid for the days you worked, not the ones you didn't)

Still, this is a valid request so I am tagging it, even if I have trouble seeing a true benefit for having such a mod, especially since by your definition everything just magically "happens" on the weekend without explaination.

**Comment by jamespfluger** [comment]
I'll pick this one up. It's pretty simple given that I can just fork the existing [Autowatering](https://github.com/stellarashes/SDVMods/tree/master/Autowatering) mod and check the date. I'll also add to the config file to let the user select what days of the week they want to auto-water.

First I'm going to reach out to the original developer to ask if they wouldn't mind me making a pull request to their existing mod to add this feature. Better to contribute to an existing project than just fork it for a small change.

**Comment by jamespfluger** [comment]
### COMPLETE! You can [download the mod here](https://www.nexusmods.com/stardewvalley/mods/5463?tab=files), version 1.1.0

The config file now has options for selecting which days to perform autowatering. If you want to have crops watered only on the weekends, then you can set weekdays to `false` in the config file, and then leave the weekend days as `true`

_This was completed as part of [this pull request](https://github.com/stellarashes/SDVMods/pull/2) I made to the Autowatering mod.  
@minervamaga can you please close this?_

**Comment by jamespfluger** [comment]
I've updated the mod from scratch and it's now here:  
https://www.nexusmods.com/stardewvalley/mods/19662  

New ideas for it can be added here:
https://github.com/jamespfluger/Stardew-ModCollection/issues
