### ISSUE TITLE
Transparency for walking behind scarecrows

### ISSUE THREAD

**Issue by NasrinAtiyeh** [StardewModders/mod-ideas#413]
So, my issue with scarecrows is that they get in the way. You can't see what's behind them. If you have a ton of crops, you're more likely to forget that you didn't water/harvest them. 
I really like the design of the vanilla scarecrows, so I don't use texture edits for them.

My proposal is to take the transparency code from the trees and apply them to scarecrows. This way, people can still use this mod with texture edits.

**Comment by Pathoschild** [comment]
Bumped difficulty since you'd probably need to transpile the `Object.draw` method.

**Comment by aedenthorn** [comment]
transpile wouldn't be easy if you want to trigger it when you walk behind, but a prefix works bc there is an alpha argument in the relevant Object.draw

https://www.nexusmods.com/stardewvalley/mods/6412
