### ISSUE TITLE
Forge at home mod?

### ISSUE THREAD

**Issue by thingwithwings** [StardewModders/mod-ideas#414]
Would it be possible to add a room in the house, or preferably a craftable item that is an anvil to allow you to open geodes at home? It could be part of the final house upgrade, or even a new final one after even Pam's house, or be a very expensive item to craft.

**Comment by megmom84** [comment]
I don't know for sure but I was thinking it might be possible to use Shop Tile Framework to add Clint's geode breaking menu. You'd still have to pay, and it would seem as if Clint is in your house suddenly (creepy, right?). I'm not sure exactly if the framework has that capability but I've thought about trying it myself.

**Comment by minervamaga** [comment]
Strobe is working on this I believe, or plans to.

**Comment by strobel1ght** [comment]
https://www.nexusmods.com/stardewvalley/mods/5326
