### ISSUE TITLE
Functional Title Screen Mod (animation removal)

### ISSUE THREAD

**Issue by Zamiell** [StardewModders/mod-ideas#443]
I hate the title screen. I want a mod to make it more functional.

1) The mod should completely remove the Chucklefish intro so that it plops you to the "New", "Load", "Co-op" screen immediately.
2) The mod should remove the animation where the 4 title screen buttons pop into existence one at a time so that I can click on whatever I want immediately without having to wait.
3) The mod should remove the sliding animation completely such that when you click on "New", it immediately shows the character creation screen. (This functionality is partly accomplished via the [Fast Animations mod](https://www.nexusmods.com/stardewvalley/mods/1089), but that mod just speeds up the sliding transition instead of completely removing it.)

I will pay a commission for the creation of this mod. Just message me on Discord (Zamiel#8743) and we can work out how much you want to be paid.

**Comment by Pathoschild** [comment]
[Skip Intro](https://www.nexusmods.com/stardewvalley/mods/533) does the first two, and you can make the slide transition instant by setting a higher speed in the Fast Animations config.

**Comment by Zamiell** [comment]
Beautiful, thank you.
