### ISSUE TITLE
"Talk to your therapist, Kent" - Make it so Kent stops sending bombs

### ISSUE THREAD

**Issue by BoxDroppingManApe** [StardewModders/mod-ideas#449]
Straight forward request: I'm worried about the man with intense PTSD sending me bombs, as well-meaning as it might be, and I'd like him to stop. It'd be amazing if there were an in-game way to trigger this change, but I'd settle for just a simple list change.

**Comment by Entoarox** [comment]
Aaaaw, leave poor kent alone! It keeps his PTSD in check to make bombs, and at least he's sending them to you rather then using them himself, now isn't he? 😆

**Comment by TaliaOwl** [comment]
Hi there, 
I've made a quick mod for this, replaces the bombs with 5 grass starter, 10 basic fertiliser, or 10 copper ore. This is my first time modding, so if you have any problems, let me know! Mod is here: https://www.nexusmods.com/stardewvalley/mods/5500/
