### ISSUE TITLE
-

### ISSUE THREAD

**Issue by purrplingcat** [StardewModders/mod-ideas#450]
-

**Comment by Sakorona** [comment]
**Issues **

- Ease of Maintenance: i.e "none"
- Why out of scope: Why is JA, a fundamental framework mod for many things out of scope if everything else is in scope?

These would also need to be addressed

**Comment by Entoarox** [comment]
If we modders could agree on a single standard method for these things, we would not need framework mods at all - they would be SMAPI features.

Simply accept you will need to have frameworks installed if you want these fancy features.

**Comment by minervamaga** [comment]
OP removed request but did not close issue.
