### ISSUE TITLE
Disable the "ZZZ" animation when fishing

### ISSUE THREAD

**Issue by Zamiell** [StardewModders/mod-ideas#451]
When I am fishing, I often accidentally mistake the "ZZZ" animation that occurs at 12 AM and 1 AM with the "!" animation that displays when a fish is hooked. Thus, I end up wasting energy and have to re-cast.

My request is to please make a mod that disables this animation entirely if the player happens to be fishing. If the player is not fishing, the animation should be the same as in vanilla.

I will pay a commission for this mod; you can private message me on Discord at Zamiel#8743 and we can work out the details.

**Comment by Annosz** [comment]
Hi! I created this mod, and made it available on the [Nexus ](https://www.nexusmods.com/stardewvalley/mods/5915):) The source code can be inspected in [my repository](https://github.com/Annosz/StardewValleyModding/tree/master/StardewValleyMods/SleeplessFisherman).

**Comment by Zamiell** [comment]
are you on the stardew valley discord?
