### ISSUE TITLE
Configure Fish Pond Chum Bucket Odds?

### ISSUE THREAD

**Issue by logan97alexander** [StardewModders/mod-ideas#463]
I enjoy a cheaty mod every now and then (okay, a LOT). Maybe a mod that improved the odds of your pond fish producing roe or other products in the chum bucket each day?

**Comment by Raik176** [comment]
so like increase the amount of roe and other products and lower the time for it to produce them?

**Comment by MarcTowler** [comment]
I am happy to give this one a go

**Comment by MarcTowler** [comment]
The mod is released https://www.nexusmods.com/stardewvalley/mods/6363/
