### ISSUE TITLE
Improve the cooking, crafting and social menu's.

### ISSUE THREAD

**Issue by killkrazed** [StardewModders/mod-ideas#470]
Take note on the below, while in single player the time that these features save is real world time, while in multiplayer it would be in game time. All these issues are considerably more impactful in multiplayer.

------------ Cooking -----------------
One thing I can't stand about Stardew, and I am sure I am not alone, is the completely disorganized cooking menu. Recipes are not in any kind of memorable order, and there is no easy way to search through them whether by name, ingredient, or effect for example.

In the base game it is highly annoying, but add on a few mods and it can sap hours out of a day trying to find a recipe to cook.

So what I propose is to create a mod that can accomplish some (or all if possible) of the following:
- Sort all cooking recipe's alphabetically by default (including modded recipe's if possible).
- Add a search bar to search by name, or text in the food or description (eg: "foraging, fishing, etc").
- Add filter options to filter by effect, whether or not it has been created yet (helpful for achievements), or mod name (not sure on the logistics of this, could be possible to get the mod name from Smapi?).
- Add sort options to sort by name, selling price, health restored, energy restored, buff intensity, or buff duration.

------------------ Crafting ----------------
Likewise the crafting menu has the same faults, with the added problem of differing sizes of the items causing things to stack in weird ways (and can make smaller objects difficult to find). Again, in the base game it can be quite annoying, and with mods it gets far worse.

What I suggest for a crafting menu is this:
- Sort crafting recipe's alphabetically by default (including modded recipes if possible).
- Align items to a grid, to prevent them from disappearing in the noise.
- A search bar, for item name or description.
- Options to filter by mod, or relevant skill (eg: foraging, farming, fishing).

------------ Social --------------------
The social menu has always irked me because it sorts by highest number of hearts by default, which can make searching for specific characters time consuming (eg: on their birthdays). It would be far easier if it was an unchanging order, or there was a way to search or sort.

What I propose for the social menu is this:
- Sort alphabetically by default (including modded npc's).
- Ability to change sort order between alphabetical and number of hearts.
- Search by name.
- Filters for Single, and non-10-heart characters.
- A "Birthday button" that toggles display of only birthday boy/girl, to make it faster to get to them and check on their favorite gifts.
- (This is a leap, but...) An option to filter only characters in the current zone, that have not been talked to yet, or not been gifted yet (2 options).

**Comment by Traehgniw** [comment]
There is/used to be a mod, better crafting menu, that had tabs for crafting items, sorted by stuff like edibility!

**Comment by KarBoy2314PL** [comment]
please split every single little thing into a separate issue
