### ISSUE TITLE
Dinosaur Sound Mod (Using Custom Music?)

### ISSUE THREAD

**Issue by photonbeam17** [StardewModders/mod-ideas#472]
Every single animal except for the dino makes a sound when you pet them. It's really weird that the dino doesn't though. So perhaps someone can make a dinosaur sound mod for the dino when you pet it. Thanks

**Comment by KarBoy2314PL** [comment]
no one hasn't really managed to make a api for new sounds so this might not be possible for now

**Comment by kdau** [comment]
Custom Music has had support for non-music sounds for a little while now, although that part isn't documented
