### ISSUE TITLE
Mead depends on honey quality

### ISSUE THREAD

**Issue by watchiam** [StardewModders/mod-ideas#48]
Actual mead quality depends heavily on the honey used, but this isn't the case for SDV.
Not sure if it would be better to add a different new item for each type of flower honey, or whether it could be done by fudging the wine mechanics.

**Comment by Jonqora** [comment]
This has been done by a couple mods, [here's one](https://www.nexusmods.com/stardewvalley/mods/5767) that's not broken currently.
