### ISSUE TITLE
Maps Framework that labels installed maps for increased map compatibility 

### ISSUE THREAD

**Issue by Balmmaker** [StardewModders/mod-ideas#480]
Installing a new map should have a way for it to be seen by other mods without each mod being required to write specific code that enables it.

For example, if the greenhouse or bathhouse is changed to a custom map, {{greenhouse}} and {{bathhouse}} should be enough for it to be found.  Maps could include data which includes valid tiles for npcs to stand and warp points so it can easily be included and NPCs will always stand on a valid tile. This could be extremely useful for larger projects like SVE which constantly alter maps and create compatibility issues.

Additionally, specific areas that are compatible for placement of buildings could also be described in the framework so new buildings can easily be added to maps

**Comment by Pathoschild** [comment]
Hi! Maps are already visible to all mods as soon as they're added, and they already have properties which manage where players/NPCs can walk, where the warp points are, etc. I'm not sure what this suggestion would change?
