### ISSUE TITLE
Way Less Flower Colors

### ISSUE THREAD

**Issue by Balmmaker** [StardewModders/mod-ideas#482]
A mod where flowers such as poppies, summer spangle and tulips all come in a wide variety of colors and quality meaning a small plot of flowers can clog up your inventory in a hurry.  A mod that reduces the the variation of color down to 1 for each flower type would be amazing -- and make flowers so much less annoying.

Additional reductions in color variation for the PPJA farmer to florist (https://www.nexusmods.com/stardewvalley/mods/2075) would be an additional expansion upon this idea.

**Comment by minervamaga** [comment]
There are already two solutions to this problem - Magic can reduce quality to normalize and Crop Color Combiner can normalize quality and color both.  In addition, as the stickies on F2F state, we have very strict permissions on the mod and cannot alter it drastically.  Closing this issue.
