### ISSUE TITLE
Journey of the Prairie King Co-op

### ISSUE THREAD

**Issue by ShadowExtreme** [StardewModders/mod-ideas#483]
Basically like the Abigail hearth event but with friends online, money could be shared/seperated, as long as it works online I am fine with it

**Comment by CoxinhaX** [comment]
Here https://www.nexusmods.com/stardewvalley/mods/12750?tab=description :D

**Comment by scayze** [comment]
Exists now :) https://www.nexusmods.com/stardewvalley/mods/16030
