### ISSUE TITLE
Lore-friendly JojaMart

### ISSUE THREAD

**Issue by HaxtonSale1** [StardewModders/mod-ideas#484]
What does JojaMart do, anyway? Anything they do gets completely outshined by Pierre's - it's strange that such inept corporation nearly put Pierre's out of competition. 

We can do better. 

- Joja opens 24hr?
- Joja sells Tortillas, Oil and Vinegar now. In addition to that, basic ingredients (flour, sugar, rice, oil, vinegar, +tortillas) are cheaper in Joja than in Pierre's: -25% before membership, -50% after. 
- Sells instant foodstuffs, such as Canned Fish (can be used in cooking recipes), JojaMeal, CarboCones, etc. Pre-processed veggies that can substitute actual veggies in a cooking recipe. Blue Alien ENERGY that gives you temporary boost but then slows you down afterwards. Bottled water, even. The stuffs they have in their shelves, basically. 
- Make them try to take over as many people's jobs as possible. Make them sell baits, tackles, furnace fuels, basic (and advanced?) sprinklers.

**Comment by f-a-u-s-t-i** [comment]
Here is something a bit similar to what you're requesting but only changing the prices
https://www.nexusmods.com/stardewvalley/mods/2658

**Comment by f-a-u-st** [comment]
This mod changes JojaMart prices to be more lore-friendly. Not entirely what you're looking for but somewhat in that direction.

https://www.nexusmods.com/stardewvalley/mods/2658

**Comment by LenneDalben** [comment]
I've created Joja Has Extra Stocks, using Shop Tile Framework (STF). It adds the tortillas, oil, vinegar, the fishing gear (including bait), and coal https://www.nexusmods.com/stardewvalley/mods/6371
