### ISSUE TITLE
DCBurger style icons for SVE

### ISSUE THREAD

**Issue by f-a-u-st** [StardewModders/mod-ideas#489]
Pretty straight forward. I really like the DCBurger icons and I would love if there were icons for the SVE npcs in the same style. I know it's a lot to ask, but if you're an artist capable of this and willing to spend time to do this I would appreciate it a lot. 

- DCBurger Portraits: https://www.nexusmods.com/stardewvalley/mods/4745

- SVE: https://www.nexusmods.com/stardewvalley/mods/3753

I'm willing to help with planning out the npcs, making the images fit the right size, testing etc. if needed. You can message me on discord (ｆａｕｓｔ#3518)

**Comment by overwritten** [comment]
Hi! This already exists in two variations -- one by Lunakatt and one by Slobbery :)

https://www.nexusmods.com/stardewvalley/mods/9029 (Lunakatt)
https://www.nexusmods.com/stardewvalley/mods/10504 (Slobbery)
