### ISSUE TITLE
Remove/disable specific sounds (ie constant buzzing in summer)

### ISSUE THREAD

**Issue by jacsisjacs** [StardewModders/mod-ideas#498]
While some of the ambient sounds are super relaxing, the buzzing bees in summer drive me mad.  I found a nexusmod to remove eating and drinking sounds, but for me the constant droning sets my misophonia off worse.  The only thing I found about this noise is that there are other people who don't like it either.  A mod to control which sounds/tracks are allowed to play in the background would be super helpful!

**Comment by MindMeltMax** [comment]
I'd like to make this happen, as i've already made a small script in the past force disabling game sound because i wanted to listen to my own music.
I'll post the finished project here when i have it

**Comment by jacsisjacs** [comment]
That would be awesome, thank you!

**Comment by MindMeltMax** [comment]
Here it is,
if there are some things missing or you want something to accompany it, you can message me here.

[https://www.nexusmods.com/stardewvalley/mods/7465/](url)

**Comment by jacsisjacs** [comment]
That was quick! Thank you so much <3

**Comment by LenneDalben** [comment]
Another mod that is specific to only the buzzing in summer is [Custom Summer Sounds.](https://www.nexusmods.com/stardewvalley/mods/7652)

**Comment by jacsisjacs** [comment]
Good to know, thanks, Lenne!
