### ISSUE TITLE
Hair Files

### ISSUE THREAD

**Issue by HopeWasHere** [StardewModders/mod-ideas#50]
I've got a lot of different hair styles, too many to use on one xnb. So I made a male hairstyle file, and a female hairstyle file. I was wondering if it would be possible to have the game load the corresponding hairstyle file based on the gender you pick. This would essentially double the amount of hairstyles that would be available to the player. Currently I have to choose whether I'm playing the game as exclusively female, or exclusively male before I start up a new game or the hairstyles look silly. Maybe there's another way to solve this (admittedly silly) problem?

**Comment by Entoarox** [comment]
Replacing the texture is easily possible, but I am uncertain if it would have a use, a look at the code shows some weird behaviour when it comes to splitting male & female hair... At the other hand, I dont see anything that would stop you from making the texture bigger :confused:
You can add more width (96 pixels at a time, for all 4 directions) or more height (32 pixels at a time), as long as you fill in all hair styles, or you will end up with bald hair styles.

**Comment by HopeWasHere** [comment]
As far as I'm aware there is a limit to how many hairstyles the game will allow on a single file. I believe only a total of 336 hairstyles work, however I haven't tried expanding the canvas to the left or right.

**Comment by HopeWasHere** [comment]
[SMAPI-latest.txt](https://github.com/StardewModders/Modding-Ideas/files/1347259/SMAPI-latest.txt)
So making the file wider doesn't seem to work. I have the file as long as the game allows and increased the width.

**Comment by Entoarox** [comment]
The texture cannot be bigger then 4096 by 4096 pixels in size, any bigger then that in any direction and the issue happens.

**Comment by pcsbx** [comment]
Will texture slots index automatically if the file is made wider than the original?

**Comment by Acerbicon** [comment]
I'm pretty sure that hope is right about 336 being the max the game recognizes. I've made my hairstyles.xnb the largest possible for testing, and the game still only shows 336 hairs, despite the fact that there are quite  a bit more hair files in that space.

Also, pcsbx, from my testing it does automatically shift the index if the file is made wider. However, considering the limit to the number of hairs, it's sort of pointless to bother with it.

**Comment by Pathoschild** [comment]
Stardew Valley 1.5 added support for [custom hairstyles](https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.5#Custom_hairstyles) which don't have that limit.
