### ISSUE TITLE
Alternate spouse/housemate room for Krobus

### ISSUE THREAD

**Issue by Zoombini50** [StardewModders/mod-ideas#519]
One of these days I will resist Leah's wonderfulness and ask Krobus to be my housemate. He is _so adorable._ I am told, however, that his special room is a sewer block. Not only does this stink up my virtual farmhouse (ha ha), but surely the little guy deserves better.

I propose Krobus get a new room with a nice cave theme, based off the mines where his more aggressive shadow brethren dwell. Alternatively, perhaps something shadow/space/cosmos-y, a la the [Void Chonkins](https://staticdelivery.nexusmods.com/mods/1303/images/3640/3640-1552787468-111766875.jpeg) in the Chonkins mod.

Either way, he could decorate with sparkly things, void things, human knickknacks that don't quite fit the decor, maybe one of those Signs of the Vessel he sells… if there's a window, it should have blackout curtains. He's still sensitive to sunlight. :)

**Comment by lemurkat** [comment]
I'll give this one a go but I'll need someone else to test it.

**Comment by Zoombini50** [comment]
I can test! :) I do have a save in which I was working on befriending Krobus so I could be roommates with him. I'll just fire it back up.

**Comment by Zoombini50** [comment]
I've been reading through Krobus's in-game dialogue and have an additional suggestion: since he likes humidity, a small steamy soaking pool/hot spring for him! (Need not be functional in-game, just relaxing-looking.)

**Comment by lemurkat** [comment]
Done. will be added to my Nicer Sewer mod as an additional choice.
