### ISSUE TITLE
Escape Rope

### ISSUE THREAD

**Issue by 4Kissa** [StardewModders/mod-ideas#527]
**Its such an simple idea, but i dont have any coding background.**
If you happen to be an Pokemon fan, you would recognize this item. 

If **I** would make it; The sprite would be an pile of rope with an hook attached to it, when used in an cave, it teleports player to the ladder in the cave entrance. If used in skull caverns, would teleport player to the skull cavern door. There could be fancy animation of the character throwing the rope up and climbing it. But it work with out it too? It could consume some energy, as in climbing a rope takes some energy. Buying this item from Dwarf or Marlon would make sense. Price wouldnt be too high as its not that useful. But it has its uses.

**Please do something with this idea, and if you happen to do. I beg you to message me in discord! Kissa#5999**

**Comment by Bifibi** [comment]
Hi, we are the developers from the SkullCavernElevator and love your idea (also big fans of Pokemon ;)). So we decided to start working on this.

**Comment by Bifibi** [comment]
Mod is implemented: https://www.nexusmods.com/stardewvalley/mods/8576
