### ISSUE TITLE
Couch Potato

### ISSUE THREAD

**Issue by Draylontis** [StardewModders/mod-ideas#534]
add The slow recover energy effect from MP if you like sit on a couch watching tv or with a book or something.

**Comment by MindMeltMax** [comment]
I can work on this.

**Comment by MindMeltMax** [comment]
https://www.nexusmods.com/stardewvalley/mods/6778
It's done

**Comment by Pathoschild** [comment]
I think the idea was more about energy recovery when you're sitting/reading, rather than lying in bed which a mod already existed for. (Especially with the upcoming Stardew Valley 1.5 update, which seems to add support for sitting without mods.)

**Comment by MindMeltMax** [comment]
Yes I heard about that mod yesterday. I am going to update the mod when 1.5 comes out
