### ISSUE TITLE
Hermes Boots

### ISSUE THREAD

**Issue by Draylontis** [StardewModders/mod-ideas#551]
Boots that give you like a speed boost when equipped but have no defenses.

**Comment by Annosz** [comment]
I will start working on this mod, I think it's a very immersive addition to the game!

**Comment by overwritten** [comment]
I made this mod! It's not Hermes Boots, but it's called Sonic Shoes :3 
https://www.nexusmods.com/stardewvalley/mods/10226

Enjoy!
