### ISSUE TITLE
Auto Attack Against Monsters

### ISSUE THREAD

**Issue by toxicToxophilite** [StardewModders/mod-ideas#563]
Basically, a port of what mobile naturally does for PC version of stardew, just start swinging once the monster is in range, in the direction of the monster. I'm bad at combat, so this would be nice without being too cheaty.

**Comment by X3n0n182** [comment]
Hey, a bit late but I'll give this a go! Will keep you posted

**Comment by X3n0n182** [comment]
Done! It only has minor animation issues but quite functional! https://www.nexusmods.com/stardewvalley/mods/7258
