### ISSUE TITLE
Limit number of events in a day

### ISSUE THREAD

**Issue by itsbenter** [StardewModders/mod-ideas#572]
Tired of two events in a row and then two more in the same day?

I tend to see a lot of events in one day. This could be annoying because of the interruptions, make the player less appreciate the event, and also make the other days less interesting than it could be. Hopefully limiting the number of events in a day will help with the pacing in gameplay.

I imagine it could be done by adding a counter when any event id is added to eventseen. Then make it somehow a condition when the game checking for an event to trigger. Definitely C# thing...

It would be nice to have let the player have the config to:
1. Number of events that can be seen in a day
2. Allow or disallow seeing events in a row (directly seeing one event after the other when entering a location, might be not immersive for some)
3. Exception (could be added by event ID)

Also, allow other modders to make their event an exception to this mod effect.

**Comment by TheMightyAmondee** [comment]
This is a good idea!
I'll have a go creating a mod to do this, having lots of events all at once really ruins the storytelling experience for me too!

**Comment by TheMightyAmondee** [comment]
[Event Limiter](https://www.nexusmods.com/stardewvalley/mods/10735/). 
This should do what you're after.
