### ISSUE TITLE
Negative Relationship

### ISSUE THREAD

**Issue by MonkeSupreme** [StardewModders/mod-ideas#576]
A mod where allows you to exceed below 0 down to -10 relationship. Villagers are harsher the lower their relationship with you and they will occasionally say harsh speech bubbles whenever they see you. They will also send you trash items occasionally through the mail. A negative relationship is indicated as black hearts in the villager menu. If a villager has a negative relationship, talking to them will decrease instead of increase your relationship. Like normal friendship though, it also decays to 0 overtime unless you reached the bottom cap(-10).

**Comment by AndyAllanPoe** [comment]
Yo! Someone just added this mod on nexsus! https://www.nexusmods.com/stardewvalley/mods/7502
