### ISSUE TITLE
Shoplifting

### ISSUE THREAD

**Issue by MonkeSupreme** [StardewModders/mod-ideas#577]
A mod that allows you to steal items from shops and markets. The item pool of items that can be stolen depends on the items that can be bought at that time in that specific shop but will be completely randomized just like checking the trash can. If villagers caught you stealing items in their area of vision, they will have a decrease in relationship. If the ones that caught you are the shopowners, they will give you a fine and all villagers will receive a decrease in relationship. A continuous offense might lead to a temporary ban from entering the shop.

**Comment by TheMightyAmondee** [comment]
This is an interesting idea, I might have a go at creating something like this.

**Comment by TheMightyAmondee** [comment]
I've just released the mod!

[https://www.nexusmods.com/stardewvalley/mods/8569/](url)
