### ISSUE TITLE
No Childern/Free Space

### ISSUE THREAD

**Issue by SolusUmbra** [StardewModders/mod-ideas#580]
I would LOVE it if my spouse would stop asking me for children and I could get rid of the beds and use that room for something else. So far this is the one thing about this game that drive me crazy. 
Thanks for taking a look

**Comment by Jonqora** [comment]
No Kids Ever mod: https://www.nexusmods.com/stardewvalley/mods/1464
Child Bed Config mod: https://www.nexusmods.com/stardewvalley/mods/3540

**Comment by SolusUmbra** [comment]
Thank You!
