### ISSUE TITLE
Slingshot-type weapon accepts other ammo, not just rocks and can config the way slingshot behaves 

### ISSUE THREAD

**Issue by neinn26** [StardewModders/mod-ideas#594]
It's guns and bows and crossbows basically. I saw a few more weapon mods and they all essentially work on the base of the slingshot mechanics, with rocks ammo and pretty meh battle ability. I saw the BetterSlingshot mod, but it's kinda old and doesn't allow ammo change...
I would really love it to be able to have slingshots working as normal but other weapons (guns, bows,...) working on the slingshot mechanic base, but able to have its own characteristics
I'm willing to do the texture for any of the new weapons if anyone is interested in the coding to modify the slingshot mechanic.

**Comment by CoxinhaX** [comment]
Yes, please, this is so needed, ranged weapons are scarce in this game...

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/12763
