### ISSUE TITLE
Mod Launcher for other mods?

### ISSUE THREAD

**Issue by Warilized** [StardewModders/mod-ideas#60]
I have a mod idea (SMAPI) to help player gather their mod in one place so they can launch it without remembering any hotkeys (except this mod's hotkeys ofc).

> 

	Description:
A mod that launch other mods without pressing hotkeys on the keyboard with a hotkey on the keyboard.
Mainly for mods that has an UI so your keyboards isn't littered with hotkeys. Useful for mods with conflicting hotkeys.
It also works for toggled mods like "Experience Bars". 

> 

	Features:
- A menu UI that helps manage mods with hotkeys.
- Customable tabs for categorizing mods like "Cheat", "Statistics", "Help", and many more (depends on the user and mods categories).
- [Configurable] An options to make mods more detailed, like having "Version", "Status", and "Author" to be included.
	+ A "Latest Version" mod will says in status as "Latest", "Deprecated Code" as "Deprecated", "Update Available" as it is.
	+ It fetch mods updates information from SMAPI.
- [Configurable] Remember or forget selected tab when you close the menu.
- [Configurable] Every tab has it's own hotkeys.
- [Configurable] It launch mod with a special character/symbol (unicode) character outside of the keyboard.
- [Configurable] It also can use a normal common character to be a hotkeys.

> 

	Notes:

- I once saw a youtube video of a man making his own emoji keyboards, so i figured it out, if he can type symbol with a keyboard, why not make a mod utilizing same logics? 	
- I pictured the mod to looked like this:

> 
 
![a mod capture](https://user-images.githubusercontent.com/18632642/31780339-01f6a942-b528-11e7-8ee2-e5f40c578267.PNG)

- The config files maybe will look like this:

>

	For "config.ini:
	{
      "MenuAccessKey": "L",
      "RememberTab": true,
      "DetailedInfo": true, //Setting this to true will make mods info more detailed (Optional but it'll make the modders have more recognition, which is good.)
      "ShowIconOnly": false, //Replace name string with Icon instead (Optional).
      //Other configuration can be added later if the modder have some inspiration for another features.
	}
    
	For "shortcut.ini"
	{
      "TabName": "Cheats",
      "TabKeyLaunch": "P",
      "TabIcon": "Tab1.png", //Will be used if ShowIconOnly is set to "True" (completely optional)
	  "DefaultLaunchLabels": "Launch", //You could edit it to something else, every "default" LaunchLabels will have this string as its label.
		{
		  "Moddll": "SomeMod.dll",
		  "KeyLaunch": "*Love Symbol*", //You could change this to any unicode characters
		  "LaunchLabel": "default", //You could change this to "set" or whatever you like without affecting other labels.
		},
		{
		  "Moddll": "SomeOtherMod.dll",
		  "KeyLaunch": "*Thinking Emoji*",
		  "LaunchLabel": "default",
		},
    }

- The mod will try to read others mod's manifest file to load the mods original names, version and author.
- Remembering tabs might requires the mod to write a mod save data (per character if possible).
- I don't know if it's possible to automatically set the other mod hotkey except manually modifying the mods Hotkeys through their config files (because every modders have their own way to name a variable).
- I hope it can work with another language.
- It works like this:
	+ The mod is launched by pressing a hotkeys ("L" in this case).
	+ The mod will display mod lists that has been configured.
	+ If you clicked the button, the button will act like a keyboard and type a unicode character.
	+ Other mods will intercept that keypress and will launch itself.
- This mod of course should have an open permission (for making their own config files) so other modders or user can make its own config files and uploads it to the community.
- This mod could made simpler with just configurable "ModName" and "KeyLaunch", but then it'll lack the neat mod information.

Thanks in advance.

**Comment by Entoarox** [comment]
Marking this as `status: infeasible` as without community-wide support such a mod just cant be done, and pathos has not given any indication that a feature like this is planned for SMAPI, and without that community-wide support is pretty much undoable.

**Comment by Warilized** [comment]
I though it would be feasible lol, but well it's been on my mind at least i can get it out...

I hope anyone could realizes it tho, even for a simpler one...

**Comment by KarBoy2314PL** [comment]
stumbled upon this on nexus, not sure if this is relevant
https://www.nexusmods.com/stardewvalley/mods/21

**Comment by Pathoschild** [comment]
That's a mod manager, but it's outdated now and the suggestion here is different (it's for a way to manage mod hotkeys in-game).

This idea isn't really feasible due to how mods work, so I'll close this now.

**Comment by Warilized** [comment]
Looking at right now, the community and the 
modder grew so much. Lol.

Although it is infeasible then, it is kind of feasible now. Mobile Phone mod achieved what I described in this somewhat.

Cheers
