### ISSUE TITLE
Customizable gift dialogue

### ISSUE THREAD

**Issue by lemurkat** [StardewModders/mod-ideas#611]
Allows NPCs to give specific responses if given a selected item (vanilla or json assets) instead of generic Like/dislike/love etc dialogue.
Ie: you could get a unique response (instead of disgust) when Shane is given a strange bun.
Would be extremely nifty if it could be worked in with Json Assets.

**Comment by purrplingcat** [comment]
Sounds not so much hard to implement. I can look into it when I have a some time.

**Comment by purrplingcat** [comment]
I am working on.

**Comment by purrplingcat** [comment]
It's done https://www.nexusmods.com/stardewvalley/mods/7304
