### ISSUE TITLE
Spouse visits you in the clinic when you pass out

### ISSUE THREAD

**Issue by CasualInvidia** [StardewModders/mod-ideas#615]
Just a fun little mod that makes your spouse appear at your bedside in the clinic after, you know, you nearly die by slime ambush, are rushed to /life-saving emergency surgery/, and make it out alive but just barely. Spouse character could say a few lines about being worried (or admonish you for being reckless), depending on their personality. I would like to imagine that your spouse does care about you still being alive! 

I'm a writer as a hobby, so I'm totally down to write all the dialogue, but I'm terrible with code and was unable to figure out how to build this mod myself. If any modders pick this up, I would be very happy to collaborate to write dialogue, or if they'd rather do it themselves, I'd also be happy to step back and let them run with it. 
Discord handle is @/CasualInvidia1235, feel free to write to me there if you prefer!

**Comment by lemurkat** [comment]
I've done this for my custom NPC Jasper. It's pretty easy! (there's even speial dialogue if your char happens to be pregnant at the time).
IF you want the code, I can share it with you, and you'd just have to fill in the blanks and maybe do a little editing.
Easiest way would be using i18n tokens. My Discord handle is Lemurkat#3754 if you want to message me.

**Comment by CasualInvidia** [comment]
Update!! Thanks to lemurkat, I managed to figure out how to write the mod, so I'll be working on this request myself!! I'll be closing the post with a big thanks to them for basically doing the heavy lifting and setting me up for success :^)
