### ISSUE TITLE
Disable Defend with Swords

### ISSUE THREAD

**Issue by Zamiell** [StardewModders/mod-ideas#622]
When the player has a sword (or scythe) equipped, they have the ability to right-click to enter a "defend" state.

I have a request for a very simple mod: disable the defend ability. Right-clicking should revert to doing what a right-click does when you have a e.g. pickaxe equipped - namely, interact with the object that the cursor is over.

This would be a small quality of life mod, because it is very common for players to accidently defend when holding a sword, which wastes in-game time and is suboptimal.

I will pay a bounty upon completion of this mod.

**Comment by DiscipleOfEris** [comment]
I made a mod that does this, compatible with controller or mouse+keyboard. The special actions of daggers and clubs are unaffected, and the action button when wielding a sword should be identical to any other tool when using this mod. I haven't found any side effects so far.

Source code available at https://github.com/DiscipleOfEris/NoDefendWithSword

Zip available at https://github.com/DiscipleOfEris/NoDefendWithSword/releases/tag/1.0.0
