### ISSUE TITLE
Chest + Sign

### ISSUE THREAD

**Issue by Warilized** [StardewModders/mod-ideas#626]
Basically a mod that makes chest have a sign on the body (the static part).

I have two approach in mind.
>To assign the sign, just place the item in a specialized box when opening it. If possible, don't consume the item.

or

>Having the mod display the first most item in the list.

The second option is simpler, but the first option is more versatile.
Also add an option to toggle item quality on or off.

**Comment by MindMeltMax** [comment]
This it?
https://www.nexusmods.com/stardewvalley/mods/7644

**Comment by Warilized** [comment]
Yes it is! 
Closing this issue, thanks for creating this mod.
