### ISSUE TITLE
Edit Wine products into Juice for Shane

### ISSUE THREAD

**Issue by Strix9443** [StardewModders/mod-ideas#635]
My first time submitting an idea, hopefully this is ok.

I have the Immersive Shane mod which I love, where Shane commits to being 100% sober after his 6 heart event, and alcohol becomes a hated gift.

I was thinking how cruel it was to marry Shane but then brew wine and beer on your farm right in front of him (I know he goes to the saloon still but I'm not looking to change that).

Wine is profitable and fruits are fun to grow, but not growing any fruits to process, only vegetables, just doesn't seem as fun.  

I was wondering if it were possible to edit the names of wine products to become juice instead (or maybe sparkling juice?), removing the tipsy buff as well.  I would not change the price that the 'new juice' sells for, or how long it takes to 'ferment', unless that were more difficult.  

I was thinking this could be implemented for all the fruits that are turned into wine.  (Technically pumpkins are a fruit but the game processes them into juice anyway, don't tell Demetrius).  

As for wheat>beer, honey>mead, and hops>pale ale, I think you could keep them as producing their alchoholic products because that might otherwise be more work, and you could just not process these specific crops if you didn't want to.  Additionally, you can still buy them from Gus at the Saloon and the other townspeople wouldn't have to suffer.

As for Leah and Harvey who love Wine, you could make them love the Juice instead.  Or just remove it from their loved list.  Jas, Vincent, and Sebastian already hate Juice so that could stay the same.  Leo and Penny hate Wine but Juice is fine so I guess the changes would reflect that.  

Looking at the wiki about wine...
The new Juice would also replace the wine in the Enchanter's Bundle, Missing Bundle, and Brewer's Bundle.  
I'm not sure how the new Juice would interact with the sewing machine as Wine is used to make the Black Leather Jacket, and vanilla Juice is used to create the Sports Shirt.  
Blobfish would request Juice instead of Wine.  

________________________________________

I hope this is ok for a request, if it can't be done that is ok, I just thought I would put it out there if anyone thought it might be a fun challenge.  Thank you modders!

**Comment by tiakall** [comment]
https://www.nexusmods.com/stardewvalley/mods/8820 Someone just did this mod which renames "wine" to "juice", might be what you're wanting?

**Comment by Strix9443** [comment]
Thank you tiakall for letting me know!  I guess I should close this?  I have not spent a long time here.
