### ISSUE TITLE
Spot the forage!

### ISSUE THREAD

**Issue by itsbenter** [StardewModders/mod-ideas#639]
**QoL mod that makes foraging slightly easier but not too cheaty.**

The idea to emulate the function of the tracker profession (arrow pointing to the forage) but only in a limited range from the player. It'll be nice if the range can scale with the foraging skill level (Though a static one would already be great). 

It's nice to pick up stuff from the ground but it's a hassle to walk behind the trees and to pay extra attention to spot the forages. And I thought the farmer should be able to spot when standing next to the forage anyway.

**Comment by Bpendragon** [comment]
Clarification:

Are you talking about an arrow that appears on screen pointing to forage, and not just at the edges of the screen, or something else?

**Comment by itsbenter** [comment]
I was thinking of an arrow to the forage (like it was anchored to the forage), though any type of visual to indicate it will do.

**Comment by Bpendragon** [comment]
Mod is now Complete: https://github.com/Bpendragon/ForagePointers

Also at Nexus https://www.nexusmods.com/stardewvalley/mods/7781
