### ISSUE TITLE
Mod allowing villagers to be sorted in alphabetical order

### ISSUE THREAD

**Issue by ImMakingToast** [StardewModders/mod-ideas#649]
Just that! I'd love to be able to sort villagers by alphabetical order on the heart menu. I have ridgeside village installed, so I have a lot of villagers. I'm also on year 3 so they're all around the same number of hearts which makes finding a specific villager kind of hard sometimes!

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/7871
