### ISSUE TITLE
Mod to create your own Farmer's Shop/Market.

### ISSUE THREAD

**Issue by Blindsidedubs** [StardewModders/mod-ideas#650]
I want to provide you with an idea for a mod that enables you to run your own farmer's shop/market. Npc's visit the shop throughout the day and purchase the produce you put in there.
You could use your spouses as the till manager and this would enable you to specify what you want in your shop, what you want to sell and provide a nice outlet to put the things you cook and craft back into the game other than gift tastes. :)
Just my two cents, i thought it would be an excellent idea but require a lot of work.

To complement on that - maybe add a little "pierre will not be pleased" option that after robin is finished building your shop (I'm guessing it will be her) you'll lose some friendship points with pierre and the next few chats you have with him will go through the stages of denial ("my costumers will never leave me"), anger ("how could you do that to me") and acceptance (Complement courtesy of Laura.suh)

**Comment by NanairoSuuji** [comment]
OOH that idea is quite interesting! It'll be nice to have various designs so the player can pick one of them and maybe depending on the modder's skills have a coloring option like with vanilla perhaps?

**Comment by JeremyK-Davinci** [comment]
I'm gonna work on this, can't promise anything timeframe wise but it seems fun

**Comment by MindMeltMax** [comment]
I'm gonna work on this, can't promise anything timeframe wise but it seems fun

**Comment by ceruleandeep** [comment]
I'm having a look at this

**Comment by ceruleandeep** [comment]
https://www.nexusmods.com/stardewvalley/mods/11778
