### ISSUE TITLE
sell abosolutely anything

### ISSUE THREAD

**Issue by Izuku-Midorya** [StardewModders/mod-ideas#651]
so i think it would be amazing to be able to sell anything cause how come robin and pierre get to sell furniture so i think if someone were to do the i'd be most grateful!

**Comment by AlejandroAkbal** [comment]
I have just published a mod that enables you to do this if you toggle a setting!

The setting is located in the file "config.json" and is named something like "check if item can be sold".

Check it out
https://www.nexusmods.com/stardewvalley/mods/7854
