### ISSUE TITLE
Clothing Catalog

### ISSUE THREAD

**Issue by LenneDalben** [StardewModders/mod-ideas#653]
It's a bit cheaty, sure, but it'd be a nice option for those of us who aren't super big on the tailoring system to be able to buy vanilla clothes. For balancing, could make each item cost money, which would be cool, and more like shopping, than going the furniture catalog route. Although if it's easier to just have it be a high up front cost and then the clothes are free like the furniture catalog, that's also fine o:

**Comment by aedenthorn** [comment]
Mobile Catalogues has this now!

**Comment by Pathoschild** [comment]
(Here's the [Mobile Catalogues page](https://www.nexusmods.com/stardewvalley/mods/6543).)
