### ISSUE TITLE
Date and Marry everyone

### ISSUE THREAD

**Issue by Izuku-Midorya** [StardewModders/mod-ideas#654]
hello and i would like someone to create a mod that simply lets you date and marry everyone who lives in pelican town

**Comment by LenneDalben** [comment]
[Multiple Spouses](https://www.nexusmods.com/stardewvalley/mods/6227) allows you to marry all the marriage candidates. It doesn't turn every NPC into a marriage candidate though.

**Comment by BlazeGamesYT** [comment]
SivsMarriageMod has that. including heart events. And new dialogue.

**Comment by BlazeGamesYT** [comment]
But its very outdated
There is an updated version here: [https://www.nexusmods.com/stardewvalley/mods/3054](Looking for love
)

**Comment by Pathoschild** [comment]
Making _every_ NPC marriageable would be difficult for a single mod, but you can combine [Free Love](https://www.nexusmods.com/stardewvalley/mods/10021) (which lets you marry multiple roommates/spouses) with mods that makes individual NPCs marriageable (like [The Robin Romance Mod](https://www.nexusmods.com/stardewvalley/mods/3239)).
