### ISSUE TITLE
Talk with NPCs while sitting in a chair

### ISSUE THREAD

**Issue by LenneDalben** [StardewModders/mod-ideas#659]
I imagine this is definitely a SMAPI mod but I'm not sure about difficulty. I'd love to be able to chat up nearby NPCs while sitting in a chair. I thought of it while sitting on a barstool at the saloon, thinking it'd be nice to not have to stand up just to talk to Shane, when he's right there.

**Comment by GrunTodd** [comment]
Hi, I saw this post and thought I'd try to make the mod - I've just uploaded it to Nexus, it's called 'Action Sitting'.

**Comment by LenneDalben** [comment]
That's awesome, thank you! ❤️

**Comment by Pathoschild** [comment]
Direct link: [Action Sitting](https://www.nexusmods.com/stardewvalley/mods/10943).
