### ISSUE TITLE
Custom Cooking/Cooking System Overhaul

### ISSUE THREAD

**Issue by Warilized** [StardewModders/mod-ideas#66]
It's a shame that custom crops from "Custom Crops" mod (and also meats from "Butcher Mod") doesn't have any use beside as an extra income and restores energy. 
I liked Custom Crops mod very much; so in order to custom crops usable in cooking , cooking mod needs to be developed.

> 

	Description:
A mod that overhaul cooking system. Adds an ability to add custom recipes for cooking.

> 

	Features:
- Ability to make custom recipes with custom crops, and meats from butcher mod.
- Ability to specify what buffs and how much energy a custom food can restore.
- Ability to buy a recipe

> 

	Optionals:
- Overhaul cooking system so it can works like Harvest Moon (with utensils and stuff)
- Utensils is bought from Clint (a.k.a Blacksmith)*.
- An ability to add additional ingredient so food can have qualities; 
	- The more ingredient with good qualities, the more likely it would produce a better quality food.
- An ability to experiment in cooking (Experimental Cooking).
- Custom foods gift tastes for villagers.
- Ability to be gifted a recipe (May require "MailFramework" mod)
- Ability to learn recipe from TV (may require "CustomTV" mod, and require custom recipes modder to add their own dialogue. (can be separate mod/optional files))

*Utensils doesn't count as an item (like axe or pickaxe). When you buy them, it automatically added to cooking menu. 

> 

	How it works:
- This mod works by scanning a recipe ingredient (Crops IDs/ meats ID(?)).
	- If user had them, the mod then processed it to food.
	- Else, the mod will display a pop-up window on mouse over what is needed (Crops ID or Meat ID).
- Viola, a food (or custom foods)

(Optionals)
- For how "optional" works, user need to specify what type of cooking they want, "according to recipe", or "Experimental Cooking"
	- Then they need to specify what utensil they need to cook things.
	- Then the user choose what ingredient they want to adds.
	- If it succeeded they got food (or custom food)
	- If it failed they get "Food Fiasco" (Make it pixelated censor for an extra laugh), the effect will be random, can be good but mostly bad.
- Experimental cooking will result in learning new recipe if the user had not having it already.
- In case doing experimental cooking and the recipe is an exact same match but the foods is different, the food user get will be ether of them but they get notified that they learn an extra recipe out of creativity or something.
- This mod should work with "Chest Anywhere" mod when choosing ingredient
- TBD

> 

	Notes:
- The mod may need it's own "Mod Save File" for every "Save files".
- The mod may need a workaround when it doesn't recognize (or doesn't have required custom crops) an ingredient so it doesn't crash, maybe replacing with a question mark(s).
- For additional ingredients for vanilla recipes, modder may need to rewrite them again so the they can accept additional ingredient (Additional Ingredient for vanilla recipes may not be a custom crops, for compability sake; but user can edit it and insert custom crops as ingredients. Maybe vanilla recipes can have it's own config folder with editable config files for every food (example: "...\CustomCooking\VanillaOverhaul")
- It also needs texture for "Food Fiasco"
- Mod folder may look like this:

> 

	CustomRecipes (Folder)
	  ...\*Recipe Name*\*required files for custom recipe*
	Saves (Folder)
	  ...\*Mod save data for every save files*
	VanillaOverhaul (Folder)
 	 ...\*Edited Vanilla Recipe*.json\
	Config.json
	CookingOverhaul.dll
	CookingOverhaul.pdb
	Manifest.json

-----------------------

Many thanks in advance for anyone that interested or wanted to develop this mod. :)

**Comment by spacechase0** [comment]
I have been working on a successor for Custom Crops, and it does support custom cooking recipes, as well as buffs on those custom food items.

**Comment by Warilized** [comment]
@spacechase0 oh it's good then, thanks for developing it also...

But can it be used by separate cooking mod? I'm thinking of something like Harvest Moon BTN cooking system where you need to buy utensils to cook and can add additional ingredient to up the food's quality.

Well, I'm still satisfied if it's only support custom cooking recipes...

**Comment by spacechase0** [comment]
Yeah, they would just need to check the cache of item IDs.

**Comment by BlatantDecoy** [comment]
https://www.nexusmods.com/stardewvalley/mods/1720
Completed by spacechase0

**Comment by Warilized** [comment]
This idea is pretty much satisfied by this mod https://www.nexusmods.com/stardewvalley/mods/6830

So, closing this.
