### ISSUE TITLE
Bundle Customization Framework

### ISSUE THREAD

**Issue by SpringsSong** [StardewModders/mod-ideas#662]
With the addition of randomized bundles in 1.5, any existing bundle overhauls were broken and the migration guide on the wiki says to utilize `Game1.netWorldState.Value.BundleData` instead of `Data\Bundles`. I don't know the first thing about making SMAPI mods, and I tried in vain to see where in the code you could edit this information and ended up precisely nowhere. I feel that a framework that supports content packs would probably be the best way to go about this, that way people (like myself) who may not know how to make SMAPI mods can make bundle overhauls like we could before 1.5.

**Comment by purrplingcat** [comment]
Edit `Data\RandomBundles` with Content Patcher doesn't work?

**Comment by MJA1981** [comment]
This has been corrected for most bundles via the new mod Custom Bundles
https://www.nexusmods.com/stardewvalley/mods/8258
