### ISSUE TITLE
Unofficial status for update checker

### ISSUE THREAD

**Issue by Kore-Development** [StardewModders/mod-ideas#666]
This is actually a suggestion for SMAPI itself but I couldn't find a place for SMAPI suggestions unless I'm just being dumb.

Unofficial updates at smapi.io/mods seem to have a format for unofficial updates such as 1.0.0-unofficial.1-someone. I could be wrong but when comparing the latest version according to the update key and the unofficial update format it assumes there is an update available. For example, this happens with the BJSNoClip unofficial update as far as I know. I think the update checker should instead set the status to "Unofficial" if the version in the manifest is an unofficial update. The Mod Update Menu mod should also add support for this new status like showing "Unofficial" in yellow or similar.

**Comment by Mizzion** [comment]
If done correctly, SMAPI shouldn't throw out update notices for unofficial updates. When we do them, we increase the unofficial update by one. So in your example Version 1.0.0 would become 1.0.1-unofficial.1-mizzion. That way when there is an update official or otherwise, then SMAPI knows.

**Comment by Pathoschild** [comment]
Yep, SMAPI already has special support for `-unofficial` versions. For example, `1.0.1-alpha` is considered newer than `1.0.1-unofficial.1` (even though prerelease tags are otherwise compared alphabetically). See [_Creating an unofficial update_](https://stardewvalleywiki.com/Modding:Mod_compatibility#Creating_an_unofficial_update) on the wiki for the format rules to avoid incorrect update alerts.

**Comment by Kore-Development** [comment]
I didn't know because the unofficial updates I have only added the unofficial part and not increment the version. It could also be possible an official update happened after the unofficial update. It could also be possible the unofficial update was uploaded by the original author but the update on Nexus was labeled as an official update.

**Comment by Kore-Development** [comment]
I think BJSNoClip had an unofficial update uploaded on Nexus by bunnyjumps for example.

**Comment by Mizzion** [comment]
Unofficial updates shouldn't be uploaded to nexus. We upload them to the stardewvalley forums. As for the update by bunnyjumps, that would be an official update since it's his mod.
