### ISSUE TITLE
Walk Over Tiny Stones

### ISSUE THREAD

**Issue by sandgoblin** [StardewModders/mod-ideas#669]
Heya! There are many little gray rocks scattered throughout the game, like the one by the bus stop path, that act as obstacles and can't be moved through. I know it's a silly little thing, but they drive me up the wall, and I'd like to request a mod to pass through them or walk over them like regular terrain. Noclip Mode feels a bit too drastic for what I need, and I haven't found anything that gets rid of these itty bitty nuisances yet. Thanks a million!

**Comment by judeman222** [comment]
Hey, I didn't realize this was on here, but I finished this a few days ago, it should be what you're looking for
https://www.nexusmods.com/stardewvalley/mods/8475
