### ISSUE TITLE
More fish tank capacity

### ISSUE THREAD

**Issue by Kayayak** [StardewModders/mod-ideas#670]
I find code from Objects\FishTankFurniture.cs
`		public int GetCapacityForCategory(FishTankCategories category)
		{
			int tiles_wide = base.getTilesWide();
			switch (category)
			{
			case FishTankCategories.Swim:
				return tiles_wide - 1;
			case FishTankCategories.Ground:
				return tiles_wide - 1;
			case FishTankCategories.Decoration:
				if (tiles_wide <= 2)
				{
					return 1;
				}
				return -1;
			default:
				return 0;
			}
		}`
I wonder if somebody make mod that more capacity or removes capacity for fish tanks.

**Comment by CoxinhaX** [comment]
I think this is what you want: https://www.nexusmods.com/stardewvalley/mods/11388
