### ISSUE TITLE
Increased Trash can Sale Values

### ISSUE THREAD

**Issue by Deathclaw99** [StardewModders/mod-ideas#671]
I'd like to have a mod which increases the amount of gold you get for trashing items in your inventory, preferably where it ends at 100% value for the Iridium trash can

**Comment by kumarchandresh** [comment]
Here, [Better Trash Can](https://www.nexusmods.com/stardewvalley/mods/11814)

Disclaimer: This is my first time making a mod for any game. So, if you've any issues, please do report them [here](https://github.com/kumarchandresh/StardewMods).
