### ISSUE TITLE
Retrieve items from the shipping bin

### ISSUE THREAD

**Issue by amandanicolee** [StardewModders/mod-ideas#683]
I'm looking for a mod that opens a menu with all items you've put in the shipping bin that day so you can click them to get them back and prevent them from being sold. You'd access it by clicking the shipping bin like usual when you go to sell things.

**Comment by LauraSuh** [comment]
The mod Chest Anywhere allows you to do that. It also has the function of.. well. chests anywhere XD but you may choose not to use it for that purpose. Here: https://www.nexusmods.com/stardewvalley/mods/518
If you put a lot of items (over 36 space slots), though, you'll have to take some out to reach the last ones you have put. But that is only a minor discomfort. Hope that helps
