### ISSUE TITLE
Mod to disable access to smapi console

### ISSUE THREAD

**Issue by MJA1981** [StardewModders/mod-ideas#688]
Could someone please looking into a simple mod to disable the users ability to input smapi console codes. My mod watches for and has patches to deal with cheat mods... An anti cheat system  type thing. Even as the mod author I can use smapi codes to get around the issue. I'd like to not allow that. I understand this is not a mod most will want. Nor will will it be any good to anyone trying to troubleshoot. But for a mod that doesn't want users to be able to cheat. Disabling the console is something I'd need to see happen. If anyone could do this that would be great. Thank you

**Comment by Sakorona** [comment]
(This should be in a SMAPI issues/requests pile, not here, at best)

**Comment by MJA1981** [comment]
Ok thank you
