### ISSUE TITLE
Easier way to pick up path pieces. 

### ISSUE THREAD

**Issue by FoggyWizard** [StardewModders/mod-ideas#689]
Using your pickaxe is time and energy consuming beyond necessity, especially when you're trying to repave a gravel path winding through your whole farm into a stone or crystal one, or moving a long path a few tiles to the left. We need an easier way, be it with a zero-energy use tool or a hotkey to turn on the ability to just pick them up like furniture or otherwise, of picking up a lot of path pieces quickly and efficiently.

**Comment by JudeRV** [comment]
This seems easy enough, I think I'll take it up

**Comment by JudeRV** [comment]
Done! https://www.nexusmods.com/stardewvalley/mods/8775
