### ISSUE TITLE
Community Center from anywhere

### ISSUE THREAD

**Issue by Kjay9558** [StardewModders/mod-ideas#691]
I was using the chests anywhere mod, which got me thinking: A mod that allows me to donate from anywhere would be nice. I think it could be implemented using the given menu for checking the community center progress once the inventory is opened. This might be an easy one, however I could be mistaken.

Another idea would be a donation bin, similar to the shipping bin, items thrown inside would be donated at the end of the day. This would obviously be a bit harder to implement. 

I couldn't find a mod like this, please tell me if a mod like this already exists.

**Comment by LenneDalben** [comment]
[Junimos Deposit Anywhere](https://github.com/Zoryn4163/SMAPI-Mods/releases) lets you add items to Community Center bundles from anywhere using the built-in bundles menu from your inventory, but be careful not to complete a bundle in your inventory, or the game will crash. And yes it still works in 1.5 :)

**Comment by Kjay9558** [comment]
Thanks a lot @LenneDalben :D I didn't knew this one.
