### ISSUE TITLE
New Death Penalty System

### ISSUE THREAD

**Issue by Jason9896** [StardewModders/mod-ideas#696]
Just a quick idea to have the death penalty be adjustable. Primarily where you are sent after death.

The player would no longer lose any items upon death, and instead the player will be sent to a reasonable location. The time passing mechanic would no longer be necessary either. If the player has some food, they should be able to eat enough to get back to decent health, and get back in the fight if they choose.

Dying in the mines = Sent to top floor of mine, and have all health(obviously) and energy set to 1
Dying in the Skull Cavern = Sent to first level with the door, energy/health set to 1
Dying in the Island/Volcano = Get sent to the cabin/Willys boat launch, health/energy set to 1 
Dying on the farm = Get sent to farm house, health/energy set to 1 
Dying anywhere else = Sent to Harvey the doctor, energy/health set to 1

Options could be provided for adjustable energy loss, gold loss, or even a negative de buff to defense: jinxed, that lasts  for a longer duration than the one cast by the shadow shaman.

**Comment by Pathoschild** [comment]
[Custom Death Penalty Plus](https://www.nexusmods.com/stardewvalley/mods/7069) and [Customizable Death Penalty](https://www.nexusmods.com/stardewvalley/mods/1991) already have some of those options, so you could try suggesting the missing options as improvements for those mods.

**Comment by TheMightyAmondee** [comment]
I've just implemented a lot of these suggestions into [Custom Death Penalty Plus](https://www.nexusmods.com/stardewvalley/mods/7069) so this can probably be closed now. Thanks for the suggestions :)
