### ISSUE TITLE
Passive friendship point gains

### ISSUE THREAD

**Issue by lemurkat** [StardewModders/mod-ideas#698]
A way to earn friendship points by "hanging out" with NPCs. 

It feels kind of weird that you can make yourself beloved to the villagers just by sauntering up to them twice a week, giving them a parsnip and maybe saying 'hi' in passing. But imagine if you could also earn points by keeping them company. If you decided to fish next to Willy on the dock, for example, or keep Sam company on the beach when everyone else leaves him by himself on Mondays in summer, or by staying with Jas when she's alone in that big empty house cos Shane and Marnie are off at the pub?

The idea is that if you are within a set amount of tiles with an NPC for a period of in-game time, you would start to earn friendship points. Nothing extreme, maybe just one friendship point for every 10 minutes, with a cap of X amount per day. Possibly activated by reaching a certain heart level first (ie: Jas might be freaked out if an almost stranger started hanging around in her house while her guardians were away).

**Comment by JudeRV** [comment]
This seems like fun, I'll take it up!

**Comment by lemurkat** [comment]
Thanks!

**Comment by JudeRV** [comment]
Alright, it's mostly done, I just have to make it so it doesn't go above max friendship. It should be done sometime tomorrow (or today I guess, it's 03:30 lmao)

**Comment by JudeRV** [comment]
Done! https://www.nexusmods.com/stardewvalley/mods/8732/
@Pathoschild
