### ISSUE TITLE
Auto-Grabber For Truffles

### ISSUE THREAD

**Issue by gisela-mariano** [StardewModders/mod-ideas#702]
could someone make a mod that works like an **auto-grabber for truffles**?

**Comment by JudeRV** [comment]
I'll take a crack at this, hopefully I can figure something out

**Comment by tiakall** [comment]
I think the Deluxe Grabber can do that? https://www.nexusmods.com/stardewvalley/mods/7920

**Comment by gisela-mariano** [comment]
> I think the Deluxe Grabber can do that? https://www.nexusmods.com/stardewvalley/mods/7920

i'll see. thx
