### ISSUE TITLE
Selling furniture

### ISSUE THREAD

**Issue by Ninjamaid13** [StardewModders/mod-ideas#708]
I've been trying to create a mod that'll let you sell furniture, but I'm no good at writing code. I've found the original value in the game code that needs to be changed but no idea how to make a mod that changes it. If the value is switched to true it'd allow players to ship anything, including annoying furniture. Although I would put a warning not to sell primary bed as I reckon this would break the game.

		public virtual bool canBeShipped()
		{
			if (!this.bigCraftable && this.type != null && !this.type.Equals("Quest") && this.canBeTrashed() && !(this is Furniture))
			{
				return !(this is Wallpaper);
			}
			return false;
		}

**Comment by berkayylmao** [comment]
Already available at https://www.nexusmods.com/stardewvalley/mods/3782
