### ISSUE TITLE
Steven Universe Gem Warp Obelisks 

### ISSUE THREAD

**Issue by Gantros** [StardewModders/mod-ideas#718]
Probably very easy since it’s a reskin mostly, but would like obelisks replaced with Gem Warp Pads from SU. The non reskin part would involve changing its footprint so you can step up onto it before activating.

**Comment by spotteddotted** [comment]
Done! I just did the reskin part, didn't change the footprint since that's a little about my paygrade. You can find it [here.](https://www.nexusmods.com/stardewvalley/mods/10756/)
