### ISSUE TITLE
you, me, and ~~dupree~~ krobus

### ISSUE THREAD

**Issue by notaroh** [StardewModders/mod-ideas#720]
I know there are about a million mods that allow you to romance Krobus or have polyamory in Stardew. What I haven't been able to find is a mod that allows you to have Krobus move in, still as a platonic roommate, while you're married.

**Comment by ArcaneDescent** [comment]
multiple spouses

**Comment by Pathoschild** [comment]
[Free Love](https://www.nexusmods.com/stardewvalley/mods/10021) lets you have roommates and spouses at the same time.
