### ISSUE TITLE
Custom Achievement Framework

### ISSUE THREAD

**Issue by TaelFayre** [StardewModders/mod-ideas#730]
Someone already suggested extra achievements but this is much more complicated, A custom achievement framework would allow content mods to use it and add more goals for players with it, from what I checked so far it seems achievements are hard coded into the game which makes adding them to the game complicated for Content Pack modders and others that have no SMAPI or C# knowledge, and with mods like Stats as Tokens being released, many options come to mind in terms of custom achievements and rewards

**Comment by aedenthorn** [comment]
I'm going to try this

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/10047
