### ISSUE TITLE
OCD Friendly Crop Protection

### ISSUE THREAD

**Issue by ShinobiZedHead** [StardewModders/mod-ideas#731]
For me and others, it can be extremely frustrating to have the order of our neat little farms disrupted.
Weeds and debris are one thing, irritating but easily disposed of.
But there are three events that can disrupt your farm in ways that take in-game days to fix.
Meteors crashing into your crops, that one bad-luck lightning bolt that gets past your rods, and the crop fairy can all de-sync your crops.
For lightning there's safe lightning... but that mod can be unreliable for me. (Path duplication, and the occasional fried crop when I load a save.) But meteors and the crop fairy have no way of stopping them.

The solution I'd like to request is a mod that disables the crop fairy and meteorite events, and buffs lighting rods. (I checked the math lighting rods use, and as far as I can tell with my limited knowledge of coding changing the base chance to intercept from 100% to 140% should mean that lighting will always be intercepted when less than 40% of your lighting rods are full - meaning that as little as 50 lighting rods could virtually guarantee safe crops year round.)

Bonus points if meteors are prevented using a farm structure (something like the gold clock - but way cheaper), so that they still show up in the early game when your fields are small and unlikely to be hit... and the 6 iridium ore is actually useful.

**Comment by aedenthorn** [comment]
For lightning rods:

https://www.nexusmods.com/stardewvalley/mods/10631

**Comment by aedenthorn** [comment]
This should work for turning off meteorites and fairies:

https://www.nexusmods.com/stardewvalley/mods/10633

I'm working on another mod with a laser machine that will actually shoot meteorites down

**Comment by aedenthorn** [comment]
Here's Meteor Defence:

https://www.nexusmods.com/stardewvalley/mods/10633

**Comment by ShinobiZedHead** [comment]
Thank ye kindly, these should do great!
You are a blessing unto perfectionists.
