### ISSUE TITLE
Chicken sounds for pet

### ISSUE THREAD

**Issue by Traehgniw** [StardewModders/mod-ideas#741]
I have a pet replacer that turns the cat into a chicken and I'd like the option to make my pet pixel rooster cluck instead of meowing.

**Comment by ForgedBrass** [comment]
I could probably whip up something that replaces the meow sound with the chicken sounds

**Comment by Traehgniw** [comment]
thanks!

**Comment by ForgedBrass** [comment]
https://www.nexusmods.com/stardewvalley/mods/10619
