### ISSUE TITLE
Better Winter Star Gifts

### ISSUE THREAD

**Issue by lemurkat** [StardewModders/mod-ideas#748]
Happy Winter Star, here's 99 pieces of wood.
I got you some clay!
Here's a geode I found on the beach...

What if, after you've attained friendship with X amount of villagers, you actually got GOOD Winter Star gifts.
I found some seeds for you.
I thought you might like this artifact trove.
Also, improve the chances of getting the elusive tea pot!

No more clay or geodes or hunks of rock. They might be useful in year one when you're collecting as many resources as you can, but I'm practically Mayor of this town and I'd like to get something pretty. Or practical.
Not something you found quickly while you were headed to the festival.

/rant

**Comment by XxHarvzBackxX** [comment]
https://www.nexusmods.com/stardewvalley/mods/10024 :)
