### ISSUE TITLE
More easily noticable panning spot.

### ISSUE THREAD

**Issue by Jason9896** [StardewModders/mod-ideas#755]
Small idea to replace the graphic that indicates panning spots in the water. As they are now the white mist/bubble is very difficult to see, especially on 4 player co-op. This would vastly help when using the better panning mod. (Yes I know there is a radar, its just still hard as heck to see!)
![123Capture](https://user-images.githubusercontent.com/45834775/144329830-6331c246-f7d2-4030-afcd-4e986ecc5988.JPG)

**Comment by ForgedBrass** [comment]
I can do this quickly!

**Comment by ForgedBrass** [comment]
![Better_Panning](https://user-images.githubusercontent.com/97308979/148592112-0c061804-1614-4658-8199-50c609fbf711.gif)
Something like this?

**Comment by Jason9896** [comment]
Looks great thank you!

**Comment by ForgedBrass** [comment]
https://www.nexusmods.com/stardewvalley/mods/10608/
