### ISSUE TITLE
Pokemon Additions (NOT Replacers!)

### ISSUE THREAD

**Issue by BriWake** [StardewModders/mod-ideas#759]
I've had an idea floating around in my head for a mod that adds Pokemon to Stardew Valley - not just replacing the existing animals/monsters with Pokemon, but adding Pokemon and related items to the game. The idea would be to add an NPC somewhere in the game that shows up maybe once a week and will sell Pokemon eggs and Pokemon-related items. The items available would rotate like the traveling cart, though with a few staples that are always available.

Examples of items would be Small (for coops) and Large (for barns) Incubators specifically for Pokemon eggs (Or you could just add functionality to the coop/ostrich incubators?), which you purchase from the NPC under the shared name of "Odd Egg" (Though with each egg having a unique coloration and short description such as "A mysterious egg. It's quite heavy." hinting at which Pokemon is inside). They will also have an assortment of season-appropriate berry seeds for sale, and possibly also fish Pokemon that can go into fish ponds or fish tanks. All things considered, the Pokemon should be treated like they're NOT normal for the setting, with their and the NPC's origins being left mysterious. (Heck, maybe you could even involve Mr. Qi somehow?)

Below is a list of my ideas for what Pokemon could be included, keeping in mind that they should be producing items for the player to collect and use or sell. They should also have a small chance of producing one of their own eggs for any given item production. I've also included a list of berry crops from the extensive list of berries in the Pokemon series.

# Pokemon

## Coop Pokemon
Delibird (Produces a wide variety of random items, including things like metal bars or artifacts) [Egg: “It feels a bit cold.” Costs 5,000G, 7 Day Incubation]
Carbink (Produces Gemstones) [Egg: “It sparkles like a jewel.”]
Grub > Combee (Produces Honey) [Egg: “It smells sweet.”]
Buneary (Produces Deluxe Wool) [Egg: “It feels like a little bundle of energy.”]
Pansage (Produces Tea Leaves) [Egg: “It smells faintly of herbs.” Costs 1,000G]
Paras (Produces Mushrooms) [Egg: “It looks like there’s fungus growing on it.”]
Rolycoly (Produces Coal) [Egg: It feels like a rock.”]
Ducklet > Swanna (Produces Pretty Feathers) [Egg: “It’s a bit damp.”]

## Barn Pokemon
Miltank (Produces Moo-Moo Milk, can be processed into Moo-Moo Cheese) [Egg: “It’s quite heavy.”]
Audino (Produces an item of seasonal forage every day, with the possibility of fruit tree fruits similarly to the bat cave) [Egg: “It’s a bit plain, but cute.”]
Phanpy > Donphan (Produces Truffles) [Egg: “It’s a bit dirty.”]
Foongus > Amoongus (Produces Mushrooms) [Egg: “Is this some kind of seed?”]
Skiddo > Gogoat (Produces Go-Go Milk, which can be processed into Go-Go Cheese) [Egg: “It smells like fresh grass.”]
Happiny > Chansey (Produces “Lucky Eggs”, perhaps can add a luck boost when eaten or used in cooking?) [Egg: “You feel lucky just seeing it.” Incredibly long incubation/growth times, possibly 14 days each for a season-long wait?]
Wooloo > Dubwool (Produces “Deluxe Wool”) [Egg: “It feels soft.”]

## Fish Pond Pokemon
Luvdisc
Wishiwashi
Pyukumuku
Bruxish
Barboach
Feebas
Magikarp
Clamperl (Produces Pearls in Fish Pond)
Chinchou

# Crops
## Spring Crops
Oran Berry
Pecha Berry
Leppa Berry
Razz Berry
Pomeg Berry
Hondew Berry

## Summer Crops
Cheri Berry
Persim Berry
Nanab Berry
Kelpsi Berry
Grepa Berry
Liechi Berry

## Fall Crops
Chesto Berry
Rawst Berry
Lum Berry
Qualot Berry
Tamato Berry
Roseli Berry

## Winter Crops
Aspear Berry
Yache Berry

## Spring-Summer-Fall Crops
Starf Berry
Enigma Berry

**Comment by overwritten** [comment]
This is multiple ideas in one; consider splitting it into multiple issues (i.e. one about adding coop/barn pokemon, and another about adding pokemon crops).
