### ISSUE TITLE
Robin is taking a break from work

### ISSUE THREAD

**Issue by ghost** [StardewModders/mod-ideas#764]
Robin will stop construction work in the evening and will return home for the night. You will be able to give her a gift and talk to her.

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/11244

**Comment by DreadGoose** [comment]
If it's possible, could this also make it so Robin doesn't work on certain days? (Mainly her birthday, her husband's birthday, and her kids' birthdays)
