### ISSUE TITLE
Set Seedmaker Mixed Seeds odds/chance

### ISSUE THREAD

**Issue by iReisen** [StardewModders/mod-ideas#765]
Hey!
why i got the idea: I'm currently doing a long playthrough of super modded SDV with better mixed seeds and seed shortage.
However, eventually you will get to a point where you can easily sustain specific seeds for profit, which counters the point of using mixed seeds to get a variety of crops onto the farm.

Since Seedmakers have a low chance to give mixed seeds however, I'd be very happy if anyone would write a mod that lets the player adjust the odds of getting mixed seeds vs seeds of the plant you're throwing into it. Should be a fairly small mod as well, hoping someone can take the time to help me out! =)

**Comment by aedenthorn** [comment]
Here:

https://www.nexusmods.com/stardewvalley/mods/10681/

**Comment by iReisen** [comment]
Hey i'm opening this up as i was advised to do in the using-mods channel.
While the mod does what its supposed to do when operated manually (all settings in the config work, with costum crops aswell), it does not work together with automate. When the seed maker is being loaded with crops via automate, it will revert to the vanilla behavior.

After contacting the mod author they replied that they altered the vanilla code (placement action) and they don't know if its possible to make it compatible with automate on their end.

I was told to comment this here instead of the automate github page.

**Comment by aedenthorn** [comment]
I could patch Automate, I suppose, it's hardcoded in that mod as well:

https://github.com/Pathoschild/StardewMods/blob/stable/Automate/Framework/Machines/Objects/SeedMakerMachine.cs#L39

**Comment by aedenthorn** [comment]
Okay, it should work with Automate in the latest version
