### ISSUE TITLE
Sensible Watering

### ISSUE THREAD

**Issue by FlacidJellybean** [StardewModders/mod-ideas#771]
I've been searching for a mod to make it so it's not possible to water crops that are already watered, untilled soil, basically anything that doesnt need to be watered by players. 
--accidentally using your watering can is a bummer in a few different situations. 

idk if something like that exists. i havent been able to find one. 

IDK how to make mods though, you all inspire me.

**Comment by GrumpyCrouton** [comment]
Here you go. https://www.nexusmods.com/stardewvalley/mods/10998/?tab=description

**Comment by FlacidJellybean** [comment]
My hero!
