### ISSUE TITLE
Dumb but awesome mod idea: if you sit on a couch facing/near a TV the TV turns on

### ISSUE THREAD

**Issue by Niminae** [StardewModders/mod-ideas#782]
Exactly what it says. You sit on a couch near a TV and the TV turns on. Prevents having to be covering the TV with your character and maybe could open a future where we watch TV on SDV.

**Comment by Pathoschild** [comment]
[Action Sitting](https://www.nexusmods.com/stardewvalley/mods/10943) might be what you're looking for?

**Comment by Niminae** [comment]
Oho! You are correct!
