### ISSUE TITLE
Crab Traps

### ISSUE THREAD

**Issue by OddlySpecificV** [StardewModders/mod-ideas#784]
Mod that makes crab pots a rope that is unseen when submerged under water maybe a rope that hangs into the sea. This is so I can enjoy moonlight jellies more. Could make the icon look something like this
![Crab Trap](https://user-images.githubusercontent.com/102712819/160973723-50320f30-c2f2-4f4c-8082-7087179c66e6.jpg)

**Comment by aedenthorn** [comment]
maybe this is usable? https://www.nexusmods.com/stardewvalley/mods/11719/
