### ISSUE TITLE
Lighting Overhaul + Customization

### ISSUE THREAD

**Issue by AveUmbraNoctis** [StardewModders/mod-ideas#787]
I have absolutely no idea how to make mods and wouldn’t even know where to start (lol) so I need someone more experienced than I am to tell me if this is possible! I would LOVE a mod that allows you to modify or set a lighting schedule for  the braziers + lamps + wall sconces. I.E. they turn on at 5pm every day and turn off at 6am or something like that. 
The ability to set inside versus outside would be sweet too but I’m assuming there isn’t any differentiation in coding for the locations of lights so that may not be possible. 
Or a way to dim the lights maybe? Like a 25%, 50%, 75% dimness if that makes sense?

**Comment by Katknapp** [comment]
+1 to this. Honestly we need a whole lightning customization mod. I've been dying to have 1x1 place-able lanterns/light furniture with no workarounds. Just simple just short lamps, and I can't make them cos all the lamp lighting is tall (DGA). Customizable options the OP suggested would be amazing.

**Comment by aedenthorn** [comment]
I have made a mod that lets you increase / decrease the light radius and brightness, as well as add your own lights to existing or custom objects. I can upload tomorrow.

**Comment by Katknapp** [comment]
> I have made a mod that lets you increase / decrease the light radius and brightness, as well as add your own lights to existing or custom objects. I can upload tomorrow.

aedenthorn, I'm already of huge fan of yours, I use so many of your mods, but if you make my lighting dreams come true, I will be ded. I will definitely be testing /  leaving feedbacks. lol. Thank you so much for considering this.

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/14387/
