### ISSUE TITLE
Shovel Tool 

### ISSUE THREAD

**Issue by akhanson73** [StardewModders/mod-ideas#789]
I want a mod that adds a shovel to move plants around. My current idea would be the following:
- Base shovel - able to move regular crops / hoed ground. transfers the fertilizer as well as the state of growth of the crop. Useful for if you plant stuff at the beginning of a season and unlock sprinklers a few days later, for example.
- Copper shovel - lets you move tea and coffee plants (here or iron, also can move non-fully grown trees?)
- Iron shovel - allows you to move salmonberry/blackberry sized bushes 
- Gold shovel - can move trees! this is the main reason I want a mod like this, so you can pick up a tree and move it, for example into the greenhouse. I looked so hard to find a mod that does this
- Iridium shovel - able to move giant crops, for those who like their aesthetic but not where they randomly grew

**Comment by atravita-mods** [comment]
This mod does a lot of what you want already: https://www.nexusmods.com/stardewvalley/mods/2594?tab=description
