### ISSUE TITLE
Locking carpet/furnitures

### ISSUE THREAD

**Issue by oorinx** [StardewModders/mod-ideas#791]
Mod idea to add a hotkey or ability to lock carpet/furniture so we don't accidentally move it.
Everyone should know how annoying it is to accidentally pick up a dang carpet when there are a lot of furniture on top of it.
Or maybe make it so you can't pick up carpet when there's furniture on top of it.
Anything please. Begging you.. l|lorz

**Comment by atravita-mods** [comment]
My mod [here](https://www.nexusmods.com/stardewvalley/mods/10192) prevents you from moving carpets if there's something on it (and also does quite a bit more, like preventing gates from popping off). [Elizabeth's mod](https://www.nexusmods.com/stardewvalley/mods/10374) has category-by-category toggles.

**Comment by oorinx** [comment]
> My mod [here](https://www.nexusmods.com/stardewvalley/mods/10192) prevents you from moving carpets if there's something on it (and also does quite a bit more, like preventing gates from popping off). [Elizabeth's mod](https://www.nexusmods.com/stardewvalley/mods/10374) has category-by-category toggles.

OMG! Thank you so much! I was searching for "carpet" this whole time and forgot it is "rug" !! Thank you again!
