### ISSUE TITLE
Sure way of getting missed QoS recipes

### ISSUE THREAD

**Issue by Entoarox** [StardewModders/mod-ideas#8]
Per http://community.playstarbound.com/threads/best-of-queen-of-sauce.129209/

Perhaps have it so Gus sells QoS recipes you do not know 1 in-game week after she first teaches it, the price should be on the slightly expensive side, to encourage people to both pay attention to the recipes (and re-runs) rather then just "get them from Gus anyway".

**Comment by Bpendragon** [comment]
I'll take a stab at this one.

**Comment by Bpendragon** [comment]
Beta now available, full release 🔜 

https://github.com/Bpendragon/Best-of-Queen-of-Sauce/releases/tag/v1.0.0-beta.1

**Comment by Bpendragon** [comment]
Complete https://www.nexusmods.com/stardewvalley/mods/7985
