### ISSUE TITLE
Pet's Water Bowl Always Full

### ISSUE THREAD

**Issue by StardewSweetheart** [StardewModders/mod-ideas#806]
Making sure I fill my cat's water bowl stresses me out, and it makes me sad that sprinklers don't work to fill it. Any chance someone is down to make it so it's always filled and still contributing to friendship with your pet?

**Comment by invatorzen** [comment]
It was similar to an existing mod that needed to be updated so I took a shot at it. You can [check it out here](https://www.nexusmods.com/stardewvalley/mods/12161/), just make sure you edit the config file and set "DailyFilling" to true :)

**Comment by StardewSweetheart** [comment]
It works!!! Thank you so much. My heart, and my pet's bowl, is full.
