### ISSUE TITLE
Thor's Hammer

### ISSUE THREAD

**Issue by ghost** [StardewModders/mod-ideas#834]
A weapon that follows the mouse cursor, if you throw the hammer it will stay in the air until mouse click release or for a couple seconds.

Special move casts down a lightning strike in the enemy position hitting nearby enemies.

If the hammer is released it will fall in the ground, any enemy that is hit gets stuck, they won't move but you can free them by making the hammer return or instead cast special to end their suffering.

Maybe it could be battery powered? or maybe it could be a dwarf hammer powered by dwarf gadgets.

**Comment by spacechase0** [comment]
Throwable Axe partially does this. https://www.nexusmods.com/stardewvalley/mods/5097
