### ISSUE TITLE
Repel

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#849]
Adds "repel" items that prevents monsters from spawning based on player's combat level?

Repel: prevents weaker monsters from spawning.

Super Repel: prevents stronger monsters from spawning.

Max Repel: prevents any monster from spawning.

All repels could have a time limit or number of steps before it stops working.

**Comment by spacechase0** [comment]
Vanilla has oil of garlic: https://stardewvalleywiki.com/Oil_of_Garlic
