### ISSUE TITLE
A skill revolved around dumpster diving or just a revamp for the trash cans.

### ISSUE THREAD

**Issue by Ylgnik** [StardewModders/mod-ideas#862]
Checking the trash cans are always worth it early game, but after you get so far, you barely find yourself checking them, What about a skill that revolves around checking the trash cans and maybe even trash itself? 

Like say for reaching level 5, you can choose from 2 skills: The first one can be one that lets you get a small bonus to the loot you can find while the second one can be a higher chance at getting items in general or getting trash from them (If the trash revamp is part of it or something) Don't know how the 10th skills would work, but something about the same, just higher chances?

**Comment by sketchbook22** [comment]
Great news!  I've heard about someone working on a mod that includes this recently.
https://discord.com/channels/137344473976799233/156109690059751424/1030586271535464528

**Comment by drbirbdev** [comment]
Apparently I've released this mod.  Didn't know it was a request though 

https://www.nexusmods.com/stardewvalley/mods/14073

**Comment by Ylgnik** [comment]
Awesome, thank you!
