### ISSUE TITLE
Legendary Fish Ponds

### ISSUE THREAD

**Issue by APerchal** [StardewModders/mod-ideas#871]
I'm aware there are mods existing already that allow fishing up multiple legendary fish. However, I'm a huge fish pond fan, and would love to be able to raise legendary fish in ponds. I'd be glad to help create their reproductive rate and drop statistics after studying the Stardew Wiki is that helps reduce the amount of work. And another way to help ensure the legendary fish ponds aren't too OP would be making their original pond capacity start at 1, of course. And what would also be an incredible attention to detail is to have their pond water color change when their population is high enough, sewer green for the mutant carp, frigid blue for the Glacierfish, and that gentle green for the Crimsonfish. I don't think the Qi quest fish that enable the second generation of the legendries would be necessary for the mod, though, since that would add much more work.

If someone would be willing to help make legendary fish possible to be used in fish ponds through mods, I would be incredibly happy.

**Comment by APerchal** [comment]
Looks like this feature is a part of the Walk of Life mod! I recommend checking it out!

**Comment by tiakall** [comment]
This is now possible in vanilla!

**Comment by ImJustBag** [comment]
Oh don't worry, I knew before the update adding it dropped LOL. Had insider info.
