### ISSUE TITLE
Play Prairie King with NPCs.

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#876]
Just like in Abigail's event, there was a fun 2 player mode, I wish other npcs could play it too, maybe even to the final level? this could make the mini game more interesting to play!

Player would invite npcs to play arcade in the saloon or play online prairie king if they have machine?

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/12750/

**Comment by CoxinhaX** [comment]
Thank you!
