### ISSUE TITLE
Horse Wagon

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#887]
A wagon that connects to the horse, it has a big storage, player can put tons of items or even sleep inside?

Could work with custom horse skins, be the new traveling merchant.

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/7911?tab=files implements the inventory

**Comment by CoxinhaX** [comment]
> https://www.nexusmods.com/stardewvalley/mods/7911?tab=files implements the inventory

That is very great! I will close this.
