### ISSUE TITLE
Fishing Net

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#889]
Late game tool for fishing, player throws it on water to catch tons of fish, has cast distance and can be used with baits.

The net could work in one of these ways:
Like a crab pot, takes a while to catch everything, player can pick the net before or wait and let it fill with fish.
Like the fishing rod, when player throws the net a mini game will start and the better you play the more you get.

Fishing net could receive upgrades like copper, iron, gold and iridium or just iridium? faster net or more fish?

Or instead fishing nets are items that can unlocked and bought in Willy's shop, he would sell nets in different sizes (like small, medium or large nets).

It catches even more treasure and other items, maybe some nets can catch new types of fish? like a giant net that catches giant fish.

Nets could get destroyed by fish or worn out.

**Comment by MindMeltMax** [comment]
I had worked on this before but could never get myself to finish it, until I saw this.
It's not exactly as you requested but it does what it says : [https://www.nexusmods.com/stardewvalley/mods/13819/](https://www.nexusmods.com/stardewvalley/mods/13819/)

**Comment by CoxinhaX** [comment]
> I had worked on this before but could never get myself to finish it, until I saw this. It's not exactly as you requested but it does what it says : https://www.nexusmods.com/stardewvalley/mods/13819/

Wow! thank you :D
