### ISSUE TITLE
Mechanic that allows lowering item quality

### ISSUE THREAD

**Issue by Serity** [StardewModders/mod-ideas#9]
For when you need to turn in stacks of items but you have half of them gold/silver because the game can't read your mind and give you normal quality

**Comment by pcsbx** [comment]
Suggesting mechanic to be implemented as a machine called Poppy Topper Z3, after what they say about tall poppies.

Blueprints could be obtained from Pierre after some suitable milestone(s), something like this:

- (Letter): "Hello $FARMER_NAME! I hear your farm is turning up quite handsomely these days, and it came to me that you might be interested in a machine I read about a little while ago. I sent you the brochure. Come visit my shop if you'd like to order it! --Pierre"

- (another letter): "Introducing PoppyTopper Z3! Does the inconsistent or exceeding quality of your farm produce and forage cause trouble? The new PoppyTopper Z3 is the answer to your call! With its astounding, delicate-yet-durable mechanisms, it can lower the quality of practically any item down to any desired level, and may even produce more lower-level items than were put in! Don't accept imitations! Only the PoppyTopper Z3 processes multiple item types in a single run without need for user input! Order yours today! Swift delivery in full working order, now at the low low price of 1,000,000 g! ..."

- (same letter continues) "... Blueprints and build-at-home licence also available. Materials not included. 20,000 g."

**Comment by HopeWasHere** [comment]
I was bored and decided to throw this machine together. It's not great, so don't worry about not using it, I don't care in the slightest.
![untitled](https://user-images.githubusercontent.com/31319352/29942096-e6bd59e8-8e51-11e7-9b21-c2888b9026d1.png)

**Comment by spacechase0** [comment]
Just FYI, Equivalent Exchange has a "Normalize" key that when pressed does this for the item you're holding. (Any leftover value is put into your wallet.)

**Comment by Lizardorb** [comment]
I'm going to try making a mod that lets you reduce the quality of items so let me know if anyone has taken on the project already. I might use some of these ideas to help me. :D

**Comment by minervamaga** [comment]
This: https://www.nexusmods.com/stardewvalley/mods/3986

and this: https://www.nexusmods.com/stardewvalley/mods/2007

Both offer ways to dequalitize items.
