### ISSUE TITLE
Halloween related

### ISSUE THREAD

**Issue by cybermonku** [StardewModders/mod-ideas#910]
Hi, 

This is my first ever post on github. I don't use it so if my profile looks bare that's why.

Anyways, I had a dream last night about stardew valley and in that dream I was playing stardew with a mod. Now, I haven't seen this mod anywhere but I could be wrong. 

The mod suggestion I have is that it is going to be halloween related. So, during the fall season at night time, the witch can come to the farm and cast a spell on the crops to make them into monsters. And the crop monsters and the witch will start attacking the player (kinda like the wilderness farm).  Also, every week you can trade with the witch. The witch will be at the road above the farm (the one that leads to robin's house). 

That's all I dreamt about, obviously alot can be tweaked with this. I just thought this was kinda interesting and I 100000000% would download this mod. 

Reference image of the crop monster:
![image](https://user-images.githubusercontent.com/109033718/178152050-ef4b376e-833e-43e3-9ac0-553961885927.png)

**Comment by CoxinhaX** [comment]
[Cropbeasts](https://www.nexusmods.com/stardewvalley/mods/6030) makes the witch turn your crops into monsters and you can get a special item too.

**Comment by cybermonku** [comment]
oh cool, i'm gonna be downloading a mod then
