### ISSUE TITLE
Paths on water

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#918]
Players can now use paths to walk on water tiles, something like this:
![path](https://user-images.githubusercontent.com/106294023/179402536-520de8ba-4810-4c44-8663-fc1cf5c9c4bc.png)

**Comment by CoxinhaX** [comment]
I think someone is working on this already

**Comment by DecidedlyHuman** [comment]
Yup, I am working on something very much like this.
