### ISSUE TITLE
Revive dead crops

### ISSUE THREAD

**Issue by Dark-Yox** [StardewModders/mod-ideas#923]
Would be nice to have a mod to revive dead crops.
I wonder if there's still some metadata after the plant dies to make the rollback possible.

**Comment by atravita-mods** [comment]
![animation](https://user-images.githubusercontent.com/94934860/181606902-5bf25afc-d664-49e7-9fd0-46365e0c5509.gif)

apparently, yes...

**Comment by Dark-Yox** [comment]
Oh you're actually working on this mod ?

**Comment by atravita-mods** [comment]
Yeah, I tend to release mods in batches though, and there's at least two more in this batch I'm polishing up.

**Comment by Shockah** [comment]
Just throwing out a link to atravita's released mod: https://www.nexusmods.com/stardewvalley/mods/15005
