### ISSUE TITLE
Remove the flash light when bombs explodes 

### ISSUE THREAD

**Issue by Dark-Yox** [StardewModders/mod-ideas#925]
When using a bomb there's a white screen for a fraction of second, it's hurtful for people with sensitive eyes especially when using many bombs at once. It should be awesome if someone can remove that flash.

**Comment by aedenthorn** [comment]
![image](https://user-images.githubusercontent.com/13594584/181309599-052ab758-8048-46d3-8ff7-1c1e4008e1f1.png)
There's an option to turn this off.

**Comment by Dark-Yox** [comment]
Oh wow I feel so dumb right now. Thank you for showing me this option.
