### ISSUE TITLE
Sprinkler Planting

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#926]
I love mods like Plant All which lets you plant in a straight line for as long as possible, or in a 3-line burst in one direction. What I'd love, though, is the ability to stand on a tile and have a mod plant all around me in a circle that's appropriate for a sprinkler, excluding my tile as the place where the sprinkler will be placed. I'm horrible with placement sometimes, so this would be a huge help, especially if it let me do something like alt + 1 for a radius of 1 around me, alt + 2 for a radius of 2, etc. It would also be nice if the mod would refuse to plant if it detected any interruptions in that circle.

**Comment by aedenthorn** [comment]
Added to Plant All

https://www.nexusmods.com/stardewvalley/mods/10482

**Comment by Bartholomue** [comment]
Thank you so much! This works perfectly.
