### ISSUE TITLE
Ostrich Mount

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#945]
A mod that replaces the horse with a ostrich.

**Comment by TheFrenchDodo-SDV** [comment]
I'm working on it!

**Comment by TheFrenchDodo-SDV** [comment]
And here it is: [Horse to Ostrich](https://www.nexusmods.com/stardewvalley/mods/13756/)

**Comment by CoxinhaX** [comment]
> And here it is: [Horse to Ostrich](https://www.nexusmods.com/stardewvalley/mods/13756/)

You are the best, I love you so much!!!
