### ISSUE TITLE
Spring 1, Year 1 Is Sunday

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#952]
Given that the game is built around the start of the week being on a Sunday, I'd love to have a mod to change the starting day of the week for a new game to be a Sunday, rather than a Monday. I tried this through using SMAPI debug (by waiting until Sunday the seventh, then setting the date to 1) and it seemed to work fine, so I'm hoping a mod can override the starting day of the week.
This would let the last day of each week (Saturday) land on a perfect multiple of 7, and the start of a new season would also coincide with forage resets.

**Comment by Bartholomue** [comment]
Just rolled a game in to summer after setting Spring 1 to a Sunday, and the game automatically reset Summer 1 to a Monday, so it doesn't look like a mod to change the first day of the game will be viable.

**Comment by aedenthorn** [comment]
them's fightin words

**Comment by aedenthorn** [comment]
![image](https://user-images.githubusercontent.com/13594584/189189460-39a24a61-1e4d-4455-99bb-6db05389d811.png)

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/13707
