### ISSUE TITLE
Move Greenhouse Any Time

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#960]
I don't really want to use the start with greenhouse mod, but I also hate not being able to move my greenhouse until it is unlocked. Would it be possible to make a mod to let me move the greenhouse while it's still locked?

**Comment by JESSEQUEST** [comment]
This would be cool. I never really end up using it until Summer/Fall on Year 2 anyway. Would be good to have the extra space close to the farm house.

**Comment by aedenthorn** [comment]
Here: https://www.nexusmods.com/stardewvalley/mods/13589/
