### ISSUE TITLE
Spiceberry Season

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#974]
How come bushes in spring and autumn get berries, but not summer? I'd like to see a mod that makes spiceberries harvestable from bushes during summer time.

**Comment by JESSEQUEST** [comment]
Mayhaps also an elderberry season in winter?

**Comment by Bartholomue** [comment]
Resolved with the Bush Bloom mod.
https://www.nexusmods.com/stardewvalley/mods/15792
