### ISSUE TITLE
The Giant Omelet

### ISSUE THREAD

**Issue by CoxinhaX** [StardewModders/mod-ideas#977]
Gus' Famous Omelet quest now has the player eating the omelet together with everyone or they gift you a piece of the omelet.

**Comment by spacechase0** [comment]
This is not at all what you requested, but this inspired me, so I'm leaving it here.
https://www.nexusmods.com/stardewvalley/mods/13852

**Comment by CoxinhaX** [comment]
> This is not at all what you requested, but this inspired me, so I'm leaving it here. https://www.nexusmods.com/stardewvalley/mods/13852

It's even better! haha
