### ISSUE TITLE
Audible Festival Start

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#979]
I've oft missed an event because I was too caught up doing something else in game. Would it be possible to tie the game event notification (today's festival has started in the town square) with an in-game sound?

**Comment by drbirbdev** [comment]
I made this mod: https://www.nexusmods.com/stardewvalley/mods/14170/

It includes customizable notification sounds, and also warnings for when festivals will end soon.

**Comment by Bartholomue** [comment]
You're the best! I sincerely appreciate you even looking at this idea, and furthermore for making it. Thank you very much for your time and effort. :)
