### ISSUE TITLE
Make Your Partner Your Winter Star

### ISSUE THREAD

**Issue by StardewSweetheart** [StardewModders/mod-ideas#985]
I'd love to be able to make my gf/bf/spouse my Winter Star gift recipient (and gift giver, if possible)! Or it could be configurable: always spouse, sometimes spouse, never spouse.

It would be great if this were compatible with [this mod](https://www.nexusmods.com/stardewvalley/mods/10024?tab=description) as well.

**Comment by drbirbdev** [comment]
I'll take a look at making this mod

**Comment by drbirbdev** [comment]
https://www.nexusmods.com/stardewvalley/mods/14164

**Comment by StardewSweetheart** [comment]
Oh my gosh, thank you so much!!!
